### ISSUE TITLE
Feature Request: Find/Replace in NoScribe Editor

### ISSUE THREAD

**Issue by glocalglocal** [kaixxx/noScribe#101]
Find (and Replace) would significantly improve the usability of NoScribe Editor when correcting or simply locating text. As a workaround, I open a file in a text editor, sometimes while working with NoScribe Editor on the same file, for Find/Replace which is not great.

**Comment by kaixxx** [comment]
Yes, I agree. It's already on my list. Good to hear that other people miss this feature too. Thank you!

**Comment by BabyFnord** [comment]
+1 very much missed!

**Comment by kaixxx** [comment]
Closing this because it is a duplicate of: https://github.com/kaixxx/noScribe/issues/96
But I will definitely try to implement this function in the next release!
