### ISSUE TITLE
Feature Request: Highlighted and/or colour text in NoScribe Editor

### ISSUE THREAD

**Issue by glocalglocal** [kaixxx/noScribe#102]
It would be very useful if NoScribe Editor supported highlighted and/or colour text in html for basic, quick annotating. 

Now, we can use bold/italics/underline but these can indicate different things semantically (eg emphasis). We can also use another application to annotate but that wouldn't work with Play and the embedded timestamps, so we will have to move back and forth between that external editor and NoScribe Editor while processing an interview.

**Comment by kaixxx** [comment]
Interesting idea, but I think it would be better to use dedicated QDA-software tools for that. I suggest QualCoder, another open-source software where I am involved in the development: https://github.com/ccbogel/QualCoder
QualCoder has an option to import audio files with transcripts. But I'm not sure if it works with the timestamps from noScribe. If you try it and make a suggestion over at the QualCoder repository how to improve the interoperability with noScribe, I will be happy to take a look.

**Comment by glocalglocal** [comment]
I have been using QualCoder for years and it's great but using it for simple highlighting of standalone, portable html files is an overkill and would tie the file to Qualcoder's database while losing NoScribe's all-important timestamps functionality. If there are no plans to add this to NoScribe Editor I will have to use am html editor instead. Not a problem.
