### ISSUE TITLE
Fix for loop of repeating text

### ISSUE THREAD

**Issue by kaixxx** [kaixxx/noScribe#110]
### Discussed in https://github.com/kaixxx/noScribe/discussions/109

<div type='discussions-op-text'>

<sup>Originally posted by **mael-lenoc** December  1, 2024</sup>
Hi, 
I've repeatedly ran into the issue of getting stuck in a loop of repeating text, using the large-v2 model (precise).
I originally dealt with it by transcribing shorter sections and joining them manually, as suggested in the Readme.

But then I found out about the "condition_on_previous_text" parameter, which when set to false gave me pretty good results and so far I haven't encounter any of these loops when using it. 
Here's what it says in the faster-whisper transcribe.py file :
`condition_on_previous_text (bool): If True, the previous output of the model is provided as a prompt for the next window; disabling may make the text inconsistent across windows, but the model becomes less prone to getting stuck in a failure loop, such as repetition looping or timestamps going out of sync.`

So I've added the parameter to the list of parameters of `model.transcribe` on line 1189, so it now reads :

```
segments, info = model.transcribe(
                        self.tmp_audio_file, language=whisper_lang, 
                        beam_size=1, temperature=0, word_timestamps=True, 
                        initial_prompt=self.prompt, vad_filter=True, condition_on_previous_text=False,
                        vad_parameters=dict(min_silence_duration_ms=200, 
                                            threshold=self.vad_threshold))
```

and that does the trick.

Perhaps it would be good to have the option added in the GUI so people can choose whether to use it or not ?
</div>

**Comment by kaixxx** [comment]
Disabling `condition_on_previous_text` is generally not a good idea since the consistency of the transcribed text will suffer. But it is indeed a last-resort solution for the annoying problem of getting stuck in a loop. I'll have to think about how to integrate this as an option in noScribe, if possible. One elegant solution could be to apply this automatically once repeating text is detected. But I'm not sure if this could have negative side effects. 

Do you have any audio causing this problem that you could share with me (confidentially via email at kai.droege <äd> hslu.ch)? I don't have any examples to reproduce the looping problem, atm.

**Comment by mael-lenoc** [comment]
Sure, I'll send you an example.
I've tested on a 30min interview in French, with both the option enabled and disabled (restarting the transcription after the repeating loop point to have a complete transcript), and I don't see a strong difference in terms of accuracy.
There's a couple of times where it seems that previous context could have been useful to avoid improper transcriptions, but there were errors in other places with the option set to "True".
So all in all, given that I have to manually check the transcript anyway, I find it more useful to avoid the repetition issue.

**Comment by kaixxx** [comment]
Thank you for sending the example file. This allowed me to improve the looping-prevention inside the transcription routine. I'm now using a build in feature of whisper that tries to recover from a repetition by setting `condition_on_previous_text` temporarily to false (beside other measures). Your example now runs through without issues. It's difficult to prevent looping altogether, but this should be a significant improvement. 
I will include the new routine in the upcoming release of noScribe vers. 0.6
