### ISSUE TITLE
Transkription wiederholt sich/hängt an mehreren Stellen

### ISSUE THREAD

**Issue by BabyFnord** [kaixxx/noScribe#13]
Während der Transkription scheint es einen _Hänger_ gegeben zu haben – wie bei einer zerkratzten Schallplatte wiederholt sich die gleiche Stelle mehrmals, springt irgendwann weiter, hängt wieder ... 😲 

![noScribe Fehler](https://github.com/kaixxx/noScribe/assets/39904614/fbd32ce9-fa94-46f7-bad6-6e762051faa1)

Könnte das durch eine Überlastung des Rechners kommen, wenn andere (Renderarbeit) Prozesse zu Engpässen führen? Zumindest scheint das Stoppen anderer Prozesse keine Abhilfe zu bringen, noScribe bzw. whisper.cc aus diesem Zustand zu führen. Folglich hilft nur Abbrechen und Neustarten der Transkription 😞 . Wenn bereits ein paar Stunden vergangen sind, ist das schade. Gibt es Erfahrungen bzw. Do's'n'Don'ts diesbezüglich?

**Comment by kaixxx** [comment]
Dieses "Hängenbleiben" bei langen Audiofiles ist ein bekanntes Problem dieser KI und leider noch nicht vollständig gelöst. Ein Workaround hier im letzten Punkt: https://github.com/kaixxx/noScribe#factors-influencing-the-quality-of-the-transcription

Übrigens: Wenn man die Transkription abbricht, ist der bis dahin erreichte Stand trotzdem im Zieldokument gespeichert. Erst ein erneuter Start der Transkription überschreibt diese Datei.

**Comment by BabyFnord** [comment]
Ah, RTFM – danke für die Erinnerung 😉. Gibt es einen Richtwert, wie lange die Segmente max. sein sollten?

**Comment by kaixxx** [comment]
> Gibt es einen Richtwert, wie lange die Segmente max. sein sollten?

Nein, das habe ich bisher nicht genauer ausprobiert.

Ich habe den Hinweis auf dieses Problem jetzt etwas prominenter platziert, in einer neuen Sektion "Known Issues" im Readme.
