### ISSUE TITLE
Pausing

### ISSUE THREAD

**Issue by Quidam2k** [kaixxx/noScribe#15]
With larger files, the process can take several hours. Would it be possible to pause the process, freeing up resources for other tasks without canceling?

**Comment by kaixxx** [comment]
No, that would be very difficult to implement. 
But if you cancel the process, the already transcribed text will still be saved in the selected file. Copy this file (to prevent it beeing overridden) and restart the transcription later with a new "Start" value. You can than join the resulting transcripts manually.

**Comment by Quidam2k** [comment]
Got it. If it's not easy then the workaround you describe is fine. Thanks!
