### ISSUE TITLE
Using WhisperX project for Huge performance increase

### ISSUE THREAD

**Issue by metheofanis** [kaixxx/noScribe#18]
Hello,
I would like to suggest to integrade and use the whisperX project: https://github.com/m-bain/whisperX
Using large model, I'm getting 17X speed on my poor man's GPU. It also does speaker diarisation and much better audio alignment than original whisper.

**Comment by kaixxx** [comment]
Hi, thank you for the suggestion. 
I am aware of this project and took some inspiration from it. The approach is very similar: Both whisperX and noScribe use pyannote for speaker diarization. We both do not use the original whisper, but a faster implementation (whisper.cpp in my case, "faster-whisper" in the case of whisperX). 
The main difference: WhisperX has a much more sophisticated approach to combine pyannote and whisper, including jet another AI and quite a few intermediate processing steps. I am using a simpler and faster approach that seems "good enough" for our purpose, but we will see. 
GPU-support is also available in whisper.cpp but not yet implemented in noScribe. It only works with Nvidia-cards that support CUDA so I am not sure how many people in my userbase would benefit from that. But yeah, if you have such a card it can give a nice boost in speed.
Right now, I am focussing more on the user interface and making noScribe robust and stable on a wide variety of hardware configurations.
That beeing said: I plan on switching to quantized models which have the potential to improve the performance quite an bit.

**Comment by metheofanis** [comment]
Thanks!
