### ISSUE TITLE
Impement transcript review macro for LibreOffice

### ISSUE THREAD

**Issue by menelic** [kaixxx/noScribe#19]
Thank you for an important project - I appreciate the social science focus and the thoughtful integration into MS Word. Please consider implementing this for LibreOffice to make NoScribe a truly open local transcription tool that can be used with free software. Not requiring an MS Word license would make this accessible to many more users.

**Comment by kaixxx** [comment]
This is a very good suggestion. I was not aware that LibreOffice also has a macro language and even supports MSWord-VBA commands to some extend. I will put this on my list of additional features (which keeps growing...).

**Comment by menelic** [comment]
Great! Please consider making your feature list public for example by documenting planned milestones https://github.com/kaixxx/noScribe/milestones linked to open issues such as this one. This allows others to more easily provide specific suggestions or code

**Comment by kaixxx** [comment]
> documenting planned milestones

Publishing milestones is always dangerous. People might expect that you reach them... ;)
But honestly, you are right. Making my ideas for the future of noScribe more public might encorage people to help. I will think about that.

**Comment by kaixxx** [comment]
Update: With version 0.4b, I have completly moved away from MS Word and word macros. NoScribe now includes it's own editor and outputs html which can be opened in LibreOffice directly.
