### ISSUE TITLE
How do I enable timestamps, I'm struggling

### ISSUE THREAD

**Issue by MrShinyBoots** [kaixxx/noScribe#27]
Hi there i love noscribe it is incredibly useful, however timestamps are not enabled by default. i located the config.yaml and the "whisper_extra_commands" line however what is the correct formatting and command?

i presume the option  must be -nt / --no-timestamps and somehow setting this to false 

but  everything i have tried just results in a failed transcription, i cant work out the correct formatting.

e.g

whisper_extra_commands: '--no-timestamps=false' 

does not work, sorry to be annoying but i would really like to be able to automate my timestamps as well as speaker recognition 

Many thanks

**Comment by kaixxx** [comment]
Hi, the timestamps are actually there, but they are embedded into the final docm-file. I wanted to be extra clever here ;) If you open the document in Word (and allow the embedded macros to run), you can go to any place in the transcript, press ctrl+space and the corresponding audio will play.
If you want to see the actual timestamps, go to insert > bookmarks. You will see a long list of bookmarks like "ts_34560_35800". The two numbers indicate the beginning and end of the bookmarked text in milliseconds. 
Putting visual timestamps in the "hh:mm:ss" format directly into the text is currently not possible, sorry. Others have suggested this too. I will include it as an option in the next version of noScribe which will be released within the next few weeks.
