### ISSUE TITLE
NoScribe not Utilizing NVIDIA Graphics Card

### ISSUE THREAD

**Issue by mohammedalsayegh** [kaixxx/noScribe#34]
Hello,

I'm currently working with two systems, each equipped with different graphic card drivers supporting CUDA 12.2 and 12.3, respectively, utilizing Tesla M40 and RTX 2060 Super. However, it seems that NoScribe is configured to use the CPU by default. 

Is there a way to specify the preferred graphic card in any of the configuration files? Notably, one of the systems has both an ATI and an NVIDIA M40 card.

![image](https://github.com/kaixxx/noScribe/assets/40126750/c5b5bcf4-d771-4371-84b7-d1f81dd68698)

![image](https://github.com/kaixxx/noScribe/assets/40126750/bfdeff99-2337-4bd8-8562-60d162063837)

**Comment by kaixxx** [comment]
I had to disable CUDA support for now since it was causing crashes. But I will look into this in the future. Problem is that I don't have a NVIDIA card to test this on. So I may come back to you and ask for help. 

Meanwhile, if you are able to run noScribe from source you could also enable CUDA support quite easily (assuming you are on Windows): 
- In the file "config.yml" in the user config directory (on windows: C:\Users<username>\AppData\Local\noScribe\noScribe\config.yml), change "pyannote_xpu" from "cpu" to "cuda"
- In noScribe.py, line 1008, change "whisper_device" from "cpu" to "cuda"

-> This should do the trick. You must have the cuda enabled version of PyTorch installed though. I'm curious to hear if it works 😀

**Comment by mohammedalsayegh** [comment]
> I had to disable CUDA support for now since it was causing crashes. But I will look into this in the future. Problem is that I don't have a NVIDIA card to test this on. So I may come back to you and ask for help.
> 
> Meanwhile, if you are able to run noScribe from source you could also enable CUDA support quite easily (assuming you are on Windows):
> 
> * In the file "config.yml" in the user config directory (on windows: C:\Users\AppData\Local\noScribe\noScribe\config.yml), change "pyannote_xpu" from "cpu" to "cuda"
> * In noScribe.py, line 1008, change "whisper_device" from "cpu" to "cuda"
> 
> -> This should do the trick. You must have the cuda enabled version of PyTorch installed though. I'm curious to hear if it works 😀

* Could you share requirement.txt packages list of your conda environment setup?

Here what I have at the moment, I am trying to build it under venv snadbox with python 3.11 + (PyTorch 2.1.1 and CUDA 12.1),

```
> python -m venv .\noScribe_venv
> .\noScribe_venv\Scripts\activate
```
Through trial and error, I somehow managed to create packaging list that semi work with pyinstaller 

```
> pip3 install pyinstaller librosa gradio tqdm regex requests packaging numpy tokenizers speechbrain AdvancedHTMLParser customtkinter appdirs cpufeature python-i18n faster_whisper pyannote.audio

> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

> pyinstaller --clean noScribe_combined.spec
```
* I have copied app assets such as {noScribeLogo.ico, ffmpeg.exe} from the git repository directory to where pyinstaller packaged noScribe in sub directory, `noScribe-0.4.1\dist\noScribe` 

* I have also copy the model from released packaging of noScribe.

I've made some progress in getting it to work, but I'm encountering errors when enabling 'Speaker detection,' which appears to be related to Pyannote, even though I've downloaded the necessary packaging. 

If there's a way to make Pyannote speaker identification part work with the CPU while keeping the Whisper AI side functioning with the GPU, it would help alleviate the overhead. Alternatively, considering switching to the tiny model of Whisper AI to make a bit faster. How can I achieve this?

```
Speaker identification...
Loading pyannote
Error in step 2 - identifiying the speakers.
```
![image](https://github.com/kaixxx/noScribe/assets/40126750/3c59596f-2311-4870-8577-37e51e2e6074)

if you have a hint to a possible solution, I would love to try!

**Comment by mohammedalsayegh** [comment]
This is how `noScribe_combined.spec` look like as I have to modify the dir in the file 
```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import collect_dynamic_libs
from PyInstaller.utils.hooks import collect_submodules
from PyInstaller.utils.hooks import collect_all
from PyInstaller.utils.hooks import copy_metadata

block_cipher = None

# noScribe:

noScribe_datas = [('./models/faster-whisper-large-v2', './models/faster-whisper-large-v2/'), 
('./models/faster-whisper-small', './models/faster-whisper-small/'), 
('./noScribeEdit', 'noScribeEdit/'), 
('./trans', 'trans/'), 
('./graphic_sw.png', '.'), 
('./LICENSE.txt', '.'), 
('./noScribeLogo.ico', '.'), 
('./prompt.yml', '.'), 
('./README.md', '.')]
noScribe_datas += collect_data_files('customtkinter')
noScribe_datas += copy_metadata('AdvancedHTMLParser')

noScribe_a = Analysis(
    ['./noScribe.py'],
    pathex=[],
    binaries=[('./ffmpeg.exe', '.')],
    datas=noScribe_datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

noScribe_pyz = PYZ(noScribe_a.pure, noScribe_a.zipped_data, cipher=block_cipher)

noScribe_exe = EXE(
    noScribe_pyz,
    noScribe_a.scripts,
    [],
    exclude_binaries=True,
    name='noScribe',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['noScribeLogo.ico'],
)

# diarize:

diarize_datas = [('./models/pyannote_config.yaml', 'models/'), 
    ('./models/pytorch_model.bin', 'models/'), 
    ('./models/torch', 'models/torch/')]
diarize_binaries = []
diarize_hiddenimports = []
diarize_datas += collect_data_files('lightning')
diarize_datas += collect_data_files('gradio')
diarize_datas += collect_data_files('lightning_fabric')
diarize_datas += collect_data_files('librosa')
diarize_datas += collect_data_files('pyannote')
diarize_datas += copy_metadata('filelock')
diarize_datas += copy_metadata('tqdm')
diarize_datas += copy_metadata('regex')
diarize_datas += copy_metadata('requests')
diarize_datas += copy_metadata('packaging')
diarize_datas += copy_metadata('numpy')
diarize_datas += copy_metadata('tokenizers')
diarize_datas += copy_metadata('pyannote.audio')
diarize_datas += copy_metadata('pyannote.core')
diarize_datas += copy_metadata('pyannote.database')
diarize_datas += copy_metadata('pyannote.metrics')
diarize_datas += copy_metadata('pyannote.pipeline')
diarize_binaries += collect_dynamic_libs('pyannote')
diarize_hiddenimports += collect_submodules('pyannote')
tmp_ret = collect_all('speechbrain')
diarize_datas += tmp_ret[0]; diarize_binaries += tmp_ret[1]; diarize_hiddenimports += tmp_ret[2]

diarize_a = Analysis(
    ['./diarize.py'],
    pathex=[],
    binaries=diarize_binaries,
    datas=diarize_datas,
    hiddenimports=diarize_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

diarize_pyz = PYZ(diarize_a.pure, diarize_a.zipped_data, cipher=block_cipher)

diarize_exe = EXE(
    diarize_pyz,
    diarize_a.scripts,
    [],
    exclude_binaries=True,
    name='diarize',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

# bring it all together:

coll = COLLECT(
    noScribe_exe,
    noScribe_a.binaries,
    noScribe_a.zipfiles,
    noScribe_a.datas,
    diarize_exe,
    diarize_a.binaries,
    diarize_a.zipfiles,
    diarize_a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='noScribe',
)
```

**Comment by gernophil** [comment]
>     * Could you share requirement.txt packages list of your conda environment setup?
Be aware that `requirements.txt` and `conda` are two completely different systems. `requirements.txt` is pip and `conda` installs conda packages (and can also install pip packages, but this should be the last step in a `conda` env and only, if you cannot avoid it.

> if you have a hint to a possible solution, I would love to try!
Can you share your log file (not sure, where to find this in windows, @kaixxx?)

> This is how `noScribe_combined.spec` look like as I have to modify the dir in the file
Do you wanna build an `.exe` file yourself? Otherwise you don't need the `.spec` file and can just run noScribe using `python`.

**Comment by kaixxx** [comment]
Nice! A few notes:
- You  can change "pyannote_xpu" in config.yml back to "cpu". This way, the speaker detection should run on the cpu and whisper still on the gpu.
- Select Quality > fast, this will use the small model and make the transcription much quicker. If you want to use the "tiny" model, the easiest way would be to change out the files in the folder for the fast model. The filenames should be the same. 
- The log file for your (failed) transcript is in the same folder as the config.yaml + /log This could give us some extra information on why pyannote failed.

**Comment by mohammedalsayegh** [comment]
> Do you wanna build an `.exe` file yourself? Otherwise you don't need the `.spec` file and can just run noScribe using `python`

I want something that isolated from installed conda and local pip python dev environment to avoid going throw same process later. If I had to uninstall them at some point, it will not mess with it + I can use archive it and use it as portable (something like KoboldAl project in portability). I think they are using microconda. But, I want to use venv.

----------------------------------------------

> * Select Quality > fast, this will use the small model and make the transcription much quicker. If you want to use the "tiny" model, the easiest way would be to change out the files in the folder for the fast model. The filenames should be the same.

thxs, this worked fantastically well! I didn't see until you mention it!!

> * You can change "pyannote_xpu" in config.yml back to "cpu". This way, the speaker detection should run on the cpu and whisper still on the gpu.

So, I am still struggle on making diarize.exe works as you describe. This is what I am getting in the log file:

```
Converting audio...
ffmpeg.exe -loglevel warning -y -ss 0ms  -i "C:/Users/ee2inf/Downloads/How Much Math is REALLY in Engineering？-(p).mp3" -ar 16000 -ac 1 -c:a pcm_s16le C:\Users\ee2inf\AppData\Local\Temp\tmpid1hfzdjnoScribe\tmp_audio.wav
Audio conversion finished

Speaker identification...
Loading pyannote
python C:\Users\ee2inf\Desktop\noScribe\dist\noScribe\_internal\diarize.py cpu "C:\Users\ee2inf\AppData\Local\Temp\tmpid1hfzdjnoScribe\tmp_audio.wav" "C:\Users\ee2inf\AppData\Local\Temp\tmpid1hfzdjnoScribe\diarize_out.yaml"
ERROR: Error in step 2 - identifiying the speakers.
ERROR: 
```
I will try to clone your released version of it.

-----------------------
> Can you share your log file (not sure, where to find this in windows, @kaixxx?)

* This is when try to run test with CPU and GPU. From the look it, it does not work under PyTourch 2.1 :

**(noScribe_venv) PS C:\Users\ee2inf\Desktop\noScribe\dist\noScribe> .\diarize.exe cuda .\tmp_audio.wav .\out.ymal**
```
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000014F7AAA5900>.
  warnings.warn(
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000014F7AAA5B40>.
  warnings.warn(
pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
torch_audiomentations\utils\io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
2023-11-22 03:26:11.1620491 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\ee2inf\Desktop\noScribe\dist\noScribe\models\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.1+cu118. Bad things might happen unless you revert torch to 1.x.
error  Repo id must be in the form 'repo_name' or 'namespace/repo_name': './models/torch/pyannote/speechbrain'. Use `repo_type` argument if needed.
```
**(noScribe_venv) PS C:\Users\ee2inf\Desktop\noScribe\dist\noScribe> .\diarize.exe cpu .\tmp_audio.wav .\out.yaml**
```
torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001D743CF5900>.
  warnings.warn(
torch\_jit_internal.py:857: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001D743CF5B40>.
  warnings.warn(
pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
torch_audiomentations\utils\io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
2023-11-22 03:26:27.8374429 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1983 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.1.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\ee2inf\Desktop\noScribe\dist\noScribe\models\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.0. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.1.1+cu118. Bad things might happen unless you revert torch to 1.x.
error  Repo id must be in the form 'repo_name' or 'namespace/repo_name': './models/torch/pyannote/speechbrain'. Use `repo_type` argument if needed.
```
So, both CPU and GPU are not working. What version of torch was used in the released one ?

**Comment by gernophil** [comment]
I know this error and I think you are missing a data file/folder. Unfortunately, I have not written down how I solved this. But IIRC it was sth. about `speechbrain` or the models. Your `.spec` file doesn't miss anything at first glance, but what I've seen is that yours
(I) contains relative paths and
(II) if you add file you do it like `('./models/pytorch_model.bin', 'models/')`. For macOS I need to to `('./models/pytorch_model.bin', 'models/.')`. Not sure, if this is the same for windows. I am also having trouble is I use `--copy-metatadata` or `--collect-data`. I haven't ruled it down yet, but I simply always use `--add-data`, which isn't the cleanest way, but at least it works. Here is my current spec file for macOS `arm64` with simplified paths. Maybe it helps.

[noScribe_arm64_spec_anonymous.txt](https://github.com/kaixxx/noScribe/files/13437244/noScribe_arm64_spec_anonymous.txt)

**Comment by mohammedalsayegh** [comment]
> (I) contains relative paths and
> (II) if you add file you do it like `('./models/pytorch_model.bin', 'models/')`. For macOS I need to to `('./models/pytorch_model.bin', 'models/.')`. Not sure, if this is the same for windows. I am also having trouble is I use `--copy-metatadata` or `--collect-data`. I haven't ruled it down yet, but I simply always use `--add-data`, which isn't the cleanest way, but at least it works. Here is my current spec file for macOS `arm64` with simplified paths. Maybe it helps.

This issue seems to be related to the `Pyannote.audio` library rather than `NoScribe` or `PyInstaller`. As `diaryize.py` failed to run directly with `2.1.1` and `3.1` versions. I have even tried multiple versions of `pytorch` both with and without cuda. However, I always encounter an error regarding Windows not supporting `torchaudio` error.

**>> python .\diarize.py cpu '.\Podcasts.wav' out.yaml**
```
C:\Users\ee2inf\Desktop\noScribe\lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
 
C:\Users\ee2inf\Desktop\noScribe\lib\site-packages\torch_audiomentations\utils\io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")

The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
torchvision is not available - cannot save figures

The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
error  type object 'SpeakerDiarization' has no attribute 'from_config_file'
```

---------------------

> The logic is: noScribe checks if it finds diarize.exe and starts the diarize.py otherwise. This way we can run it also from python.

I am having issue even when running `diarize` directly.

**Comment by gernophil** [comment]
To me this error happened when I forgot to add the folder `models/torch/pyannote/speechbrain`. According to your spec file it should be added. Could you check, if you have the folder `speechbrain` in your cloned repo?

**Comment by mohammedalsayegh** [comment]
> To me this error happened when I forgot to add the folder `models/torch/pyannote/speechbrain`. According to your spec file it should be added. Could you check, if you have the folder `speechbrain` in your cloned repo?

I mean everything seems there.
```
    Directory: C:\Users\ee2inf\Desktop\noScribe\models\torch\pyannote\speechbrain

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            5/9/2023 10:25 PM        5534328 classifier.ckpt
-a---           5/15/2023  9:39 PM              0 custom.py
-a---            5/9/2023 10:25 PM       83316686 embedding_model.ckpt
-a---            5/9/2023 10:24 PM           1920 hyperparams.yaml
-a---            5/9/2023 10:25 PM         128619 label_encoder.ckpt
-a---            5/9/2023 10:25 PM           1921 mean_var_norm_emb.ckpt

```
Is there something I am missing ?

**Comment by gernophil** [comment]
Hmm, at first glance I also don't see anything missing here. Just to rule this out, could you try using absolute paths in your spec file? So changing e.g. `('./models/torch', 'models/torch/')` to `('C:/Users/ee2inf/Desktop/noScribe/models/torch', 'models/torch/')`.

And sorry, I just read that you also have errors if you `diarize.py` directly. I think you can ignore the `The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.` warning. The other error however got me thinking and I think this is the problem. You installed the official `pyannote.audio`, but noScribe uses a fork from @kaixxx (https://github.com/kaixxx/pyannote-audio).
Install this into your venv using
```
pip install git+https://github.com/kaixxx/pyannote-audio.git
```
and try again.

**Comment by mohammedalsayegh** [comment]
> And sorry, I just read that you also have errors, if you run `diarize.py` directly. I think you can ignore the `The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.` warning. The other error however got me thinking and I think this is the problem. You installed the official `pyannote.audio`, but noScribe uses a fork from @kaixxx (https://github.com/kaixxx/pyannote-audio). Install this into your venv using
> 
> ```
> pip install git+https://github.com/kaixxx/pyannote-audio.git
> ```
> 
> and try again.

lamo, it was that! I didn't know there was a fork for the `pyannote-audio`. Even cuda works blazingly fast!!

It is even written in the readme 🤣
```
- If you want to run noScribe directly from the source, I recommend setting up pyannote and all its dependencies first. You must use my fork of pyannote, which includes a small modification run on local files only.

```

I am going write the steps here, might be useful for someone:
---------
```
python -m venv .\noScribe_venv
```
```
.\noScribe_venv\Scripts\activate
```
```
python.exe -m pip install --upgrade pip
```
```
pip install git+https://github.com/kaixxx/pyannote-audio.git
```
```
pip3 install pyinstaller librosa gradio tqdm regex requests packaging numpy tokenizers speechbrain AdvancedHTMLParser customtkinter appdirs cpufeature python-i18n faster_whisper
```
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
```
Testing with diarize:
```
python .\diarize.py cuda '.\Podcasts.wav' out.yaml
```
--------------

**Comment by mohammedalsayegh** [comment]
To make noScribe.py work, it was not possible throw pyinstaller that is due name of the sub folder which start with `_`. It trigger something in pyannote cause it to fail to excuate probably on Python 3.11.

The solution was using .bat file to execute in one click and move temp folder with in the main folder that is due Windows 11 issue. 

In run.bat 
----
```
@echo off
call .\noScribe_venv\Scripts\activate
python noScribe.py
```

While necessary change in noScribe.py,
----
[noScribe.txt](https://github.com/kaixxx/noScribe/files/13445957/noScribe.txt)

The changes in tmpdir.name & diarize_cmd, I bypassed it to a local folder and I made diarize_cmd run as shell cmd under the built environment.

CUDA was enabled for both `diarize.py` and `faster-whisper`.

and thanks a lot for the help earlier!

**Comment by kaixxx** [comment]
Great to hear that noScribe is working with CUDA! Thank you for your effort. This motivates me to include this in a next release. 
Can you tell me how big the compiled version of noScribe is in your case? I mean the whole folder that pyinstaller creates, including all the libraries, models etc. 
I did some testing before and it seems that when I include pytorch with cuda support, the app blows up to about 8GB total size. That's a bit much. It would be nice to have an option to install cuda only when it's really needed.

**Comment by gernophil** [comment]
Hey @mohammedalsayegh, I checked your workflow and I think we can shorten it a bit :). Of course, if it works it's fine, so just see this as a comment :).

> ```
> .\noScribe_venv\Scripts\activate
> ```
The [official](https://docs.python.org/3/library/venv.html) way to activate a venv in windows is for `cmd.exe`: `C:\> <venv>\Scripts\activate.bat` and for PowerShell `PS C:\> <venv>\Scripts\Activate.ps1`


> ```
> python.exe -m pip install --upgrade pip
> ```
I don't think this is necessary, but it won't harm :).


Your pip install commands are a bit different to mine. Of course, I use macOS, but some things should still also apply to you. I made an overview on the packages you installed and compared with mine. I think you can drop some explicit installs since they should be installed as dependencies anyway.
- You are missing the packages `Pillow` and `PyYAML`. Might be that they are installed as dependencies.
- And you are installing `faster_whisper`. This is a bit weird since I use `faster-whisper` and I am not sure what's the difference.
- I am not sure about the package gradio, since I don't need it and I don't see why this should be platform specific. I commented it in the attached file, but if you need it, just reactivate it.
- I also think it's not necessary to install `torchvision` at all (and `torch` itself might also be redundant, since it's a dependency of `torchaudio`)

You might try to use the attached `requirements_win.txt` and install it into a fresh venv using `pip install -r requirements_win.txt` followed by `pip install torchaudio --index-url https://download.pytorch.org/whl/cu121` afterwards manually.

[requirements_win.txt](https://github.com/kaixxx/noScribe/files/13449079/requirements_win.txt)

**Comment by mohammedalsayegh** [comment]
> Great to hear that noScribe is working with CUDA! Thank you for your effort. This motivates me to include this in a next release.
> Can you tell me how big the compiled version of noScribe is in your case? I mean the whole folder that pyinstaller creates, including all the libraries, models etc.
> I did some testing before and it seems that when I include pytorch with cuda support, the app blows up to about 8GB total size. That's a bit much. It would be nice to have an option to install cuda only when it's really needed.

@kaixxx, the venv with (all packages) + models and main repository is ~8.83GB. I think at one point, it will be very difficult to host the whole thing. Maybe, you can ship it with a package installer that clone models from `Hugging Face`.

----------------------------

> 
> Your pip install commands are a bit different to mine. Of course, I use macOS, but some things should still also apply to you. I made an overview on the packages you installed and compared with mine. I think you can drop some explicit installs since they should be installed as dependencies anyway.
> 
> * You are missing the packages `Pillow` and `PyYAML`. Might be that they are installed as dependencies.
> * And you are installing `faster_whisper`. This is a bit weird since I use `faster-whisper` and I am not sure what's the difference.
> * I am not sure about the package `gradio`, since I don't need it and I don't see why this should be platform specific. I commented it in the attached file, but if you need it, just reactivate it.
> * I also think it's not necessary to install `torchvision` at all (and `torch` itself might also be redundant, since it's a dependency of `torchaudio`)
> 
> You might try to use the attached `requirements_win.txt` and install it into a fresh venv using `pip install -r requirements_win.txt` followed by `pip install torchaudio --index-url https://download.pytorch.org/whl/cu121` afterwards manually.
> 
> [requirements_win.txt](https://github.com/kaixxx/noScribe/files/13449079/requirements_win.txt)

@gernophil I just test your `requirements_win.txt`, it seems that I include a lot of unnecessary packages. The one you have included are sufficient for it to work with no issue. The only thing that I done differently is running 
```
pip install torchaudio --index-url https://download.pytorch.org/whl/cu121
```
before 
```
pip install -r requirements_win.txt
```
that because the requirements packages download the non-cuda based tourch and I get error after trying to install the cuda one. I am not sure why it make a different but it only worked when I installed the cuda based tourch first.

* The `python.exe -m pip install --upgrade pip` was only there because I got ton of warning 🤣

**Comment by gernophil** [comment]
Ah yes, it actually might be better to install torchaudio first. IIRC from my time when I used CUDA some packages will be installed differently, if you already have CUDA packages. But that's a long time ago :).

If you do it the other way around these flags might be helpful: `--force-reinstall` (and `--ignore-installed`)
However, there's no real need to do it differently if it works with torchaudio first :).

**Comment by gernophil** [comment]
And it's great to know to requirements work. I'm gonna push it then to make it easier for others.

**Comment by mohammedalsayegh** [comment]
for more information, CUDA partially works with older nvidia cards (non-RTX). As the embedding process works fine on my 2060 super rtx. However, it doesn't seem to use GPU on older Tesla M40s. Faster-whisper works on both cards. So, I think something in torchaudio is tensorRT-based.

**Comment by gernophil** [comment]
Do you use the most recent drivers for the Tesla cards? Did you try the older CUDA version (11.8) with those cards?
(`--index-url https://download.pytorch.org/whl/cu118`)

**Comment by mohammedalsayegh** [comment]
The driver was released last month with support for cuda 12.2. Also, i can confirm that 11.8 version works on it.
```
PS C:\Users\ee2inf> nvidia-smi
Thu Nov 23 19:05:02 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.70                 Driver Version: 537.70       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla M40 24GB               WDDM  | 00000000:04:00.0 Off |                  Off |
| N/A   48C    P0             189W / 250W |   2425MiB / 24576MiB |     93%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     16600      C   ...rograms\Python\Python310\python.exe    N/A      |
+---------------------------------------------------------------------------------------+
```
It is faster than CPU, but it feels like we could go way faster if we used more VRAM to cache or more parallel instances. Can we increase chunk size or number of embeddings?

![image](https://github.com/kaixxx/noScribe/assets/40126750/eb49fe65-0aaf-48ef-aad6-73d6df23d9a6)

**Comment by gernophil** [comment]
The newest `speechbrain` version `1.0.0` does not seem to work with `noScribe` (or `PyAnnote`), we haven't figured out why yet. You need to revert back to `0.5.16`.

**Comment by kaixxx** [comment]
BTW - there is a new discussion about cuda here: https://github.com/kaixxx/noScribe/discussions/50
