### ISSUE TITLE
Crash on startup with chinese locale

### ISSUE THREAD

**Issue by jackylee1** [kaixxx/noScribe#35]
Traceback (most recent call last):
  File "noScribe.py", line 1249, in <module>
  File "noScribe.py", line 209, in __init__
  File "i18n\translator.py", line 26, in t
  File "i18n\resource_loader.py", line 103, in search_translation
  File "i18n\resource_loader.py", line 93, in load_directory
  File "i18n\resource_loader.py", line 72, in load_translation_file
  File "i18n\resource_loader.py", line 24, in load_resource
  File "i18n\loaders\loader.py", line 48, in load_resource
i18n.loaders.loader.I18nFileLoadError: error getting data from C:\Program Files (x86)\noScribe\trans\noScribe.zh-CN.yml: zh not defined

**Comment by gernophil** [comment]
Do you by any chance have Python installed on your system and can tell us the output of:
```
import locale
print(locale.getdefaultlocale()[0][0:2])
```

Otherwise as a workaround you should be able to force `noScribe` to start in English by setting `locale: en` in the file `C:\Users\AppData\Local\noScribe\noScribe\config.yml`.

**Comment by gernophil** [comment]
You also might try to change the  first line of the file `trans\noScribe.zh-CN.yml` from `zh-CN:` to `zh:`.

**Comment by gernophil** [comment]
@kaixxx: I think `i18n` has some issues with `hyphen`: https://github.com/metabase/metabase/issues/7924

**Comment by jackylee1** [comment]
Strange.no config.yml there



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 23, 2023 05:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kaixxx/noScribe] what shoud i do (Issue #35)




 
Do you by any chance have Python installed on your system and can tell us the output of:
 import locale print(locale.getdefaultlocale()[0][0:2])  
Otherwise as a workaround you should be able to force noScribe to start in English by setting locale: en in the file C:\Users\AppData\Local\noScribe\noScribe\config.yml.

**Comment by gernophil** [comment]
Ah yes, because noScribe crashes before this is created. That's sth. we need to fix.

For now simply create a plain text file and name it `config.yml` (be sure to also rename the file extension) with the above content. (`locale: en`) and try again.

**Comment by jackylee1** [comment]
I don quite get iy，do you mean i make an empty file named config.yml？any more？



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 23, 2023 16:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kaixxx/noScribe] what shoud i do (Issue #35)




 
Ah yes, because noScribe crashes before this is created. That's sth. we need to fix.
 
For now simply create a plain text file and name it config.yml (be sure to also rename the file extension) with the above content. (locale: en) and try again.

**Comment by jackylee1** [comment]
I don not get it，what do you mean



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 23, 2023 16:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kaixxx/noScribe] what shoud i do (Issue #35)




 
Ah yes, because noScribe crashes before this is created. That's sth. we need to fix.
 
For now simply create a plain text file and name it config.yml (be sure to also rename the file extension) with the above content. (locale: en) and try again.

**Comment by jackylee1** [comment]
Str object does not support item assignment



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 23, 2023 17:12 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kaixxx/noScribe] what shoud i do (Issue #35)




 
Not empty. It's needs the content locale: en and it needs to be placed in the folder C:\Users\<username&gt;\AppData\Local\noScribe\noScribe\ (sorry, the part <username&gt; was missing before).

**Comment by kaixxx** [comment]
Another option would be what gernophil mentioned in his second post:
- Open the file "C:\Program Files (x86)\noScribe\trans\noScribe.zh-CN.yml" and change the first line from "zh-CN" to "zh". Save and start noScribe again.

- If you still get an error, delete the file "config.yml" that you created

**Comment by gernophil** [comment]
> Str object does not support item assignment

More info please. What did you do? Did you make sure the file you created is not a `.txt` anymore since Windows hides known file extensions by default. Try to use the file I attached (unzip first).

[config.yml.zip](https://github.com/kaixxx/noScribe/files/13448730/config.yml.zip)

**Comment by jackylee1** [comment]
Hey my friend.since you have done the segmentation，i wonder if it could split the voice of different people and archive them&nbsp; so we can take the data to voice cloning automatically



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 23, 2023 18:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kaixxx/noScribe] Crash on startup with chinese locale (Issue#35)




  
Str object does not support item assignment
  
More info please. What did you do? Did you make sure the file you created is not a .txt anymore since Windows hides known file extensions by default. Try to use the file I attached (unzip first).
 
config.yml.zip

**Comment by kaixxx** [comment]
> i wonder if it could split the voice of different people and archive them

You could certainly do that, but that is a completly different application. I would suggest that you build your app directly with https://github.com/pyannote/pyannote-audio which it what we use to do the speaker identification and segmentation.
