### ISSUE TITLE
Empty "Start" field creates error

### ISSUE THREAD

**Issue by sebawsky** [kaixxx/noScribe#36]
Hello! I'm testing this project. When transcribing an audio, it gives me the following error:

![image](https://github.com/kaixxx/noScribe/assets/50386332/f1489cf6-6ff1-40ca-b0e7-2eb54b831adb)

I am working on a computer with Windows 11 with the following specifications:

Windows 11 Pro
AMD Ryzen 5 6-Core Processor
NVIDIA GeForce RTX 3070 Ti
RAM 38.4 GB

When I deactivate the "Speaker Detection" option, the system is able to transcribe.

How can I solve this problem?

Thanks!

**Comment by gernophil** [comment]
The problem might be, that you don't have an entry in the start field. ffmpeg warns that it's output is empty, so try putting "00:00:00" in the start field (Inicio in your case).

**Comment by kaixxx** [comment]
> The problem might be, that you don't have an entry in the start field.

This is the problem, yes. 
But it is also a bug, since it should work even if this field is empty. We are going to change this in the next version.

**Comment by kaixxx** [comment]
fixed, will be included in 0.4.5
