### ISSUE TITLE
transcribe 3 minutes video with timestamps results 3 paragraphs

### ISSUE THREAD

**Issue by bung87** [kaixxx/noScribe#37]
the speaker language is Chinese mixed with English, results to 3 paragraphs like below:
```
[00:00:00]
[00:01:00]
[00:02:00]
```
I've tried other 2 projects they are more precise but have other problems. BTW if the noScribe can ouput srt file that would be perfect.

**Comment by kaixxx** [comment]
Hmm, that's strange. Can you send me the log file for this transcript? See here (last bullet point) how to find it: https://github.com/kaixxx/noScribe#advanced-options 
You can post it here or send it to kai.droege { a t } hslu.ch

Multilingual audio is not well supported in general, but you should at least get some output. What might happen though is that whisper tries to translate the english parts into chinese or vice versa.

**Comment by bung87** [comment]
```
whisper precise beam size: 1
whisper fast beam size: 1
whisper precise temperature: 0.0
whisper fast temperature: 0.0
whisper precise compute type: default
whisper fast compute type: default
timestamp_interval: 60000
timestamp_color: #78909C
=== CPU FEATURES ===
System: MAC arm64
macOS version >= 12.3:
Using MPS (with PYTORCH_ENABLE_MPS_FALLBACK enabled)

Converting audio...
['/Applications/noScribe.app/Contents/Frameworks/ffmpeg', '-nostdin', '-loglevel', 'warning', '-y', '-ss', '0ms', '-i', '/Users/bung/Movies/lingua-py.mp4', '-ar', '16000', '-ac', '1', '-c:a', 'pcm_s16le', '/var/folders/9j/whwn7jfn3_d2s2c3w4gxx0qr0000gn/T/tmpkmr1bi1tnoScribe/tmp_audio.wav']
Audio conversion finished

Speaker identification...
Loading pyannote
/Applications/noScribe.app/Contents/Frameworks/../MacOS/diarize mps "/var/folders/9j/whwn7jfn3_d2s2c3w4gxx0qr0000gn/T/tmpkmr1bi1tnoScribe/tmp_audio.wav" "/var/folders/9j/whwn7jfn3_d2s2c3w4gxx0qr0000gn/T/tmpkmr1bi1tnoScribe/diarize_out.yaml"
segmentation: 0%segmentation: 11%segmentation: 22%segmentation: 33%segmentation: 44%segmentation: 55%segmentation: 66%segmentation: 77%segmentation: 88%segmentation: 99%segmentation: 100%segmentation: 100%segmentation: 100%speaker_counting: 100%embeddings: 3%embeddings: 7%embeddings: 10%embeddings: 14%embeddings: 17%embeddings: 21%embeddings: 25%embeddings: 28%embeddings: 32%embeddings: 35%embeddings: 39%embeddings: 42%embeddings: 46%embeddings: 50%embeddings: 53%embeddings: 57%embeddings: 60%embeddings: 64%embeddings: 67%embeddings: 71%embeddings: 75%embeddings: 78%embeddings: 82%embeddings: 85%embeddings: 89%embeddings: 92%embeddings: 96%embeddings: 100%embeddings: 100%discrete_diarization: 100%00:00:00.8 - 00:00:27.909 SPEAKER_00
00:00:28.506 - 00:01:55.8 SPEAKER_00
00:01:57.500 - 00:02:29.496 SPEAKER_00


Transcription...
Loading whisper
model loaded
Transcription...

S00 [00:00:00]:LinguaPy是一个非常有用的Python语言检测库可以用于识别给定文本的语言它能够检测超过100种不同的语言包括常见的英语西班牙语法语等以及一些较为罕见的语言如斯瓦西里语澳利亚语等Python在自然语言处理领域被广泛使用因此有一些全面的开源库可用于这个任务例如Google的CLDR和CLD3Langie FastexFastSpell Simplament和LangText不幸的是它们大多数都存在两个主要问题检测仅适用于相当长的文本片段对于非常短的文本片段如Twitter消息它们无法提供足够准确的结果参与决策过程的语言越多检测结果的准确性就越低 [00:01:00]Linear只在解决这些问题它几乎不需要任何配置并且在长文本和短文本甚至单词和短语上都能给出相当准确的结果它采用基于规则和统计方法但没有使用任何词典它也不需要连接到任何外部这个库最初是一个纯Python实现Python的快速原型设计能力对其改进起到了重要的贡献不幸的是性能和内存消耗之间一直存在权衡最初Linear的语言模型在运行时被存储在字典中这导致了较高的性能但内存消耗较大超过三级因此后来将语言模型存储在Numpy输出中而不是字典中内存消耗减少到约800Mbps但CPU性能显著下降这两种方法都不是令人满意的从2.0.0版本开始 [00:02:00]纯Python的实现被替换为Rust实现的编译Python绑定这个决定既提高了性能又减小了内存占用效率一级纯Python的实现仍然在版本一中保持最新状态版本一和版本二都将继续在PP上提供发行到数689开发的语言Python协议Apache Resource4

Transcription finished.
Saved to: /Users/bung/Movies/lingua-py.html
Duration: 4 minutes
```

**Comment by kaixxx** [comment]
Pyannote identifies three sections, but they are all assigned to the same speaker:
00:00:00.8 - 00:00:27.909 SPEAKER_00
00:00:28.506 - 00:01:55.8 SPEAKER_00
00:01:57.500 - 00:02:29.496 SPEAKER_00

Are these from different speakers? 
I once had an example where pyannote was not able to distinguish between two male voices and assigned all the sections to the same speaker. There is nothing I can do to resolve this issue because I didn't train the model myself. 

But at least noScribe transcribed the text, right? Or didn' you see this in the output: "LinguaPy是一个非常有用的Python语言检测库可以用..."?

**Comment by bung87** [comment]
only one speaker, but voice are generated through tts

**Comment by bung87** [comment]
I used one tool, maybe also based on whisper, am not sure, it split sentence by sentence like all subtitles on video in general, but it maybe use wrong encode every sentence first character is tofu. 

the subscribed results have no punctuations so I can't split it by python script. so I hope it can spilt to sentences atleast I can manually correct the subtitles.

**Comment by bung87** [comment]
I just re read the readme, yeah my needs is not this project main purpose even they are using similar technique, I understand now

**Comment by kaixxx** [comment]
If you want to create subtitles for video, there are better tools out there especially for this purpose. Take a look at https://github.com/SubtitleEdit for instance. It also supports whisper, as far as I know.

**Comment by bung87** [comment]
Thanks! it looks awesome but only windows version keep updated.
