### ISSUE TITLE
Error when Speaker Detection is set as Auto

### ISSUE THREAD

**Issue by lzmfor** [kaixxx/noScribe#48]
Issue 1: Set Speaker detection as Auto, Error. 
---
**Run noScribe directly from the source**, it works, The interface appears. Set `Speaker detection`  as `none`, it works. But when `Speaker detection` is set as "Auto", it reported an error. 

- UI interface reported: 
> Converting audio...
> Audio conversion finished
> 
> Speaker identification...
> Loading pyannote
> Error in step 2 - identifiying the speakers.

- Python console reported: 
> Traceback (most recent call last):
>   File "D:\Development\noScribe\diarize.py", line 23, in <module>
>     import yaml
> ModuleNotFoundError: No module named 'yaml'

**Have Try** 
- Required libraries installed correctly (requirements_win.txt)
  > pip install git+https://github.com/kaixxx/pyannote-audio.git
-  I confirm that `yaml` has been installed correctly
- Manually give `sys.argv` to `diarize.py` script, test it alone and it works, 
  > ... ...
  > 31 app_dir = os.path.abspath(os.path.dirname(__file__))
  > 32
  > 33 device = 'cpu'
  > 34 audio_file = '.\File_Audio\AAAAA.mp3'
  > 35 segments_yaml = 'out.yaml'
  > 36
  > 37 class SimpleProgressHook:
  > ... ...

**Issue 2:** Cuda do not work
---
- Set `Speaker detection` as `none`, avoid the above problem, make the noScribe.py work. And set `pyannote_xpu: cuda` in config. It still uses `cpu`
- Test `diarize.py` individually, set `device = 'cuda'` in the `diarize.py` file, It works and still uses `cpu`

Many thanks

**Comment by kaixxx** [comment]
# Issue 2 - cuda
I had to disable cuda since it was causing crashes. But I am working on re-introducing cuda support. It would be great if you could help with that. I don't have NVIDIA graphics in my PC so I have a hard time testing new versions. Are you on windows?

**Comment by lzmfor** [comment]
# Issue 1 solved
- Many thanks for that, **Issue 1 is solved.**
- You are correct. I am using Virtualenv in Pycharm.
- Changed it to fit my `venv`, it worked. `noScribe.py` Line 870: 
  > `... `
  > `# diarize_abspath = 'python ' + os.path.join(app_dir, 'diarize.py')`
  > `diarize_abspath = r'D:\Development\noScribe\Scripts\python.exe ' + os.path.join(app_dir, 'diarize.py')`
  > `... `
---

> ## Issue 1:
> I assume you have installed noScribe and it's dependencies in some form of virtual environment? It seems that "diarize.py" is not run in that environment. Therefore, the module yaml is not available. Look at lines 869/70:
> 
> https://github.com/kaixxx/noScribe/blob/0db4d7d32480c699a61947f9ab34e5bd5a3c0c52/noScribe.py#L870
> 
> 
> If you run noScribe from source, diarize is called with: "python diarize.py". My suspicion is that this may pick up the system installed python, not the one in you virtual environment. (I'm using Anaconda on Windows and cannot reproduce this error.)

**Comment by lzmfor** [comment]
# Issue 2 Follow-up

Yes, maybe I can help test it out
- Windows10, NVIDIA graphics card RTX 4070 Ti
- I don't know much about that. perhaps the following information would be useful
  > **Package in my Pyhton environment** >>>>>>>>>
  > torch 2.2.1+cu121
  > torch-audiomentations 0.11.1
  > torch-pitch-shift 1.2.4
  > torchaudio 2.2.1+cu121
  > torchmetrics 1.3.1

  > **nvidia-smi in Windows system** >>>>>>>>>>>>
  > NVIDIA-SMI 537.13
  > Driver Version: 537.13
  > CUDA Version: 12.2

Others
- When you say `disable cuda`, do you mean that `cuda` has been disabled in the current version? cuda can not be enabled even if the configuration file is changed to `cuda`?
- I saw on other issue pages that someone has successfully used `cuda` to run noScribe. https://github.com/kaixxx/noScribe/issues/34#issuecomment-1823681778
- Are you made some changes to the version he had at that time? Is it no longer possible to run under `cuda` like him in the current version? 

> # Issue 2 - cuda
> I had to disable cuda since it was causing crashes. But I am working on re-introducing cuda support. It would be great if you could help with that. I don't have NVIDIA graphics in my PC so I have a hard time testing new versions. Are you on windows?

**Comment by kaixxx** [comment]
# Issue 1
Great, so you confirmed that this was the problem. Du you have an idea for a more general solution that doesn't involve changing the path on every system?

**Comment by kaixxx** [comment]
# Issue 2 - CUDA

Having a cuda-enabled driver and pytorch installed on your system are the morst importand prerequisites. To enable cuda in noScribe, you must change to things:
- setting "pyannote_xpu" to "cuda" in config.yml should enable cuda-support in the first step, the speaker-recognition with pyannote
- In order to enable cuda support in the transcription-step, you have to go to line 1023 and change "whisper-device" from "cpu" to "auto" (assuming you are in Windows):
`if platform.system() == 'Windows':` 
`   whisper_device = 'auto'`

**Comment by lzmfor** [comment]
# Issue 2 solved
- Many thanks for that, Issue 2 is solved. 

> Having a cuda-enabled driver and pytorch installed on your system, make some changes as 
> * For the speaker-recognition, setting "pyannote_xpu" to "cuda" in config.yml, 
> * For the transcription, `noScribe.py` line 1023, change "whisper-device" from "cpu" to "auto" (assuming in Windows):
>   `if platform.system() == 'Windows':`
>   `   whisper_device = 'auto'`

---
I'm afraid I may not be able to offer good advice.
- Could you try to add several judgments here? Considering more situations and making them work accordingly. In my case, I run it in a virtual environment, etc.
- Or using `try`, output exact feedback if someone gets this error. The person might be able to troubleshoot a bit.

> Great, so you confirmed that this was the problem. Du you have an idea for a more general solution that doesn't involve changing the path on every system?

**Comment by lzmfor** [comment]
# Issue Summary
Both issues are well solved. thank you very much for your active responses. 👍 

For those who may encounter such problems later,
### Issue 1: Set Speaker detection as Auto, get Error.
- Check here for the solution: https://github.com/kaixxx/noScribe/issues/48#issuecomment-1966204543
> **Error as:**
> ... Error in step 2 - identifiying the speakers. ... | ... import yaml ... ModuleNotFoundError: No module named 'yaml'

---

### Issue 2: Run with Cuda | Work with Cuda | Use GPU
Using Cuda will bring significant speed boost, have a try
- Check here for the solution: https://github.com/kaixxx/noScribe/issues/48#issuecomment-1968499771

**Comment by kaixxx** [comment]
> Using Cuda will bring significant speed boost

Nice. Can you confirm that cuda works in speaker detection as well as transcription? I'll try to make this available for all in the next release.

**Comment by lzmfor** [comment]
When two items are set at the same time
1. config.yml: `pyannote_xpu: cuda`
2. noScribe.py: `whisper_device = auto`

- Transcription:  **Cuda obviously works**, and significant speed boost. `CPU` occupancy is low, `GPU` occupancy is high.
- Speaker Detection: **It seems that Cuda does not work**. It takes up both CPU and GPU occupancy at the same time. No significant speed differences were found, compared to the case when `pyannote_xpu: cpu` and `whisper_device = auto`.

> Nice. Can you confirm that cuda works in speaker detection as well as transcription? I'll try to make this available for all in the next release.

**Comment by kaixxx** [comment]
Interesting, thank you. It seems that the speaker detection is also using the GPU to some extend, but not very efficiently. I'm still going to include this in the next release.
