### ISSUE TITLE
Problem bei der Installation, noScribe auf MacOS (Intel)

### ISSUE THREAD

**Issue by jokoppino** [kaixxx/noScribe#49]
Hallo!

Ich bin überhaupt keine Expertin, aber ich habe versucht, no Scribe auf meinem Mac zu installieren, genau so wie es in den Anleitungen beschrieben ist (Intel). Leider klappt es aber nicht: Ich kann das Programm nicht öffnen, obwohl ich in den Systemeinstellungen beim Datenschutzt angegeben habe, es soll das Programm trotzdem öffnen.

Wenn ich aufs Programm klicke, sieht es einen Moment lang so aus, als würde es aufgehen, aber dann passiert nichts und im Dock erscheint es auch nicht. 

Hat jemand einen Tipp, woran das liegen könnte? Oder was ich machen muss?

Vielen Dank!

**Comment by kaixxx** [comment]
Hallo,

zwei spontane Ideen: 
- Hast du auch sicher die richtige Version installiert (noScribe_x86_64_unsigned.dmg)?
- Es könnte sein, dass du dein Betriebssystem aktualisieren musst auf die neuste Version, die Apple für deinen Rechner anbietet. Auf jeden Fall sollte es nicht älter sein als macOS 11.0. (Bitte mach eine gute Datensicherung, wenn du dein System aktualisierst.)

Hoffe, das hilft.

**Comment by gernophil** [comment]
Hey, ja das klingt danach, dass macOS zu alt ist. Kannst du mal oben link auf das Apple-Symbol klicken und dann auf `Über diesen Mac`? Und dann mal sagen, was da bei `Chip` und bei `macOS` steht?

**Comment by mdavies94** [comment]
hey all, @jokoppino - Konntest du das Problem lösen? Ich habe einen gleich alten Mac und habe das gleiche Problem. Ich habe es auch auf einem neueren Mac versucht und hatte das gleiche Problem... 
<img width="260" alt="image" src="https://github.com/kaixxx/noScribe/assets/163854222/01e03bac-662b-45b8-ba28-8187db5ff2b9">

**Comment by mdavies94** [comment]
> hey all, @jokoppino - Konntest du das Problem lösen? Ich habe einen gleich alten Mac und habe das gleiche Problem. Ich habe es auch auf einem neueren Mac versucht und hatte das gleiche Problem... <img alt="image" width="260" src="https://private-user-images.githubusercontent.com/163854222/313669717-01e03bac-662b-45b8-ba28-8187db5ff2b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NjYzMjYsIm5iZiI6MTcxMDc2NjAyNiwicGF0aCI6Ii8xNjM4NTQyMjIvMzEzNjY5NzE3LTAxZTAzYmFjLTY2MmItNDViOC1iYTI4LTgxODdkYjVmZjJiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMjQ3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTNlMWZhYTRjZDE2MDQxMGFkZjYwMzk3MTUxY2ZlNTQ0YTM1YjA4MWRjOGY0ZTQyMzI1OTgxN2JiMTI5ZjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ki9A31FbZqXcCOL75Evrg_vtalV-Q9y33oC0I6gY1UU">

@jokoppino - Könntest du die Version 4.0 verlinken, die du benutzt hast und die funktioniert hat, denn ich sehe viele in dem Ordner. vielen danke!

**Comment by gernophil** [comment]
Ich hab mal eine 0.4.5 beta auf einem alten Mac kompiliert. Vielleicht könntest du die mal testen:
https://drive.switch.ch/index.php/s/EIVup04qkSHb54j?path=%2FnoScribe%20vers.%200.4%2FmacOS%2Fx86_64%20(Intel)%2F0.4.5

Ansonsten ist hier der Link zur 0.4: 
https://drive.switch.ch/index.php/s/EIVup04qkSHb54j?path=%2FnoScribe%20vers.%200.4%2FmacOS%2Fx86_64%20(Intel)%2F0.4

**Comment by BabyFnord** [comment]
@gernophil @kaixxx 0.4.5 läuft auf Mac mini (2018) mit Ventura 13.6.5 👍. Danke dafür!

**Comment by gernophil** [comment]
Lief denn die 0.4.4 sogar auf Ventura nicht?

Danke für den Hinweis in der `plist.info`. Da muss ich mal ne Funktion schreiben :).

**Comment by melanileo** [comment]
ich habe das gleiche Problem. Ich habe es jetzt auf zwei Laptops versucht.ich habe den macOS Big Sur, Version 11.7.10. Prozessor 2.5 GHz Quad-Core Intel Core Intel Core i7, kann mir jemand helfen?

**Comment by yjeanrenaud** [comment]
by no means bin ich MacOS expert, aber vielleicht hilft das weiter.
die App startet gar nicht in der Version 0.5.0_arm64 auf einem M1 MBP.
Ob mit oder ohne Freigabe für Internet-Downloaded-Apps ändert nichts. Es kommt keine Fehlermeldung, kein Fenster, nichts.
open -n ./Application/noScribe.app führt auch zu nichts.
Die binary-Komponente aus dem Sparse selbst zu öffnen zeigt eine Fehlermeldung mit dem Python framework:
<img width="678" alt="Bildschirmfoto 2024-07-12 um 11 52 49 (002)" src="https://github.com/user-attachments/assets/bef8e56f-c7ee-4946-bbfe-3690031c6726">

**Comment by kaixxx** [comment]
Hallo Yves,
das ist seltsam. Könntest du uns noch die macOS-Version verraten? Vielleicht ist die zu alt.

**Comment by BabyFnord** [comment]
> Version 0.5.0_arm64 auf einem M1

Falscher Thread, @yjeanrenaud? Hier geht es um Intel-Macs … 💁 

Die noScribe_0.5.0_x86_64_unsigned_legacy läuft auf macMini 2018 unter macOS Ventura 13.6.7 einwandfrei samt Editor, bzw. mit Modifikationen auch auf einem MacPro5,1 unter macOS Mojave 10.14.6 (bislang noch ohne Editor).

**Comment by yjeanrenaud** [comment]
sorry, ich zieh das raus hier und kläre das mit der macOS version. War zwischen Tür und Angel und ich wollte das nur posten, um es nicht zu vergessen.

**Comment by kaixxx** [comment]
Ich hatte dieses Issue noch offen gelassen, damit es andere Leute mit einem ähnlichen Problem besser finden. Aber jetzt hat sich hier schon lange nichts mehr getan und ich werde es schließen. Danke an alle!
