### ISSUE TITLE
Error encoding

### ISSUE THREAD

**Issue by ArnaudD94** [kaixxx/noScribe#5]
Hello,

I tried to transcribe an audio in Hungarian, but the process stops after one sentence (I tried different part of the full audio and I have the same error).

This the message:

Error in step 3 - transcription
'charmap' codec can't encode character '\u0151' in position 0: character maps to <undefined>

How can I fixe this problem?

![issue_NoScribe](https://github.com/kaixxx/noScribe/assets/71450875/d5ca5bdc-0584-459d-aff6-9400943e1e6f)

**Comment by ArnaudD94** [comment]
Thanks a lot. I look forward to hearing from you.

**Comment by kaixxx** [comment]
I think I found the problem. 
Please download this version of "noScribe.exe" and put it in the main app folder (C:\Users\USERNAME\AppData\Roaming\noScribe), replacing the old version: https://drive.switch.ch/index.php/s/zdbPb58nixqg2ii
Does it work now?

**Comment by ArnaudD94** [comment]
It works perfectly! Thanks a lot.

**Comment by kaixxx** [comment]
Thank you!
Another collegue had problems with japanese characters and also confirmed that it is working now. 
The solutuion will be included in the next release which should follow in a few days.
