### ISSUE TITLE
obsolete, sorry …

### ISSUE THREAD

**Issue by BabyFnord** [kaixxx/noScribe#53]
RTFM!

**Comment by kaixxx** [comment]
Do you have one of the footswitches mentioned in your original post? Do they send a particular key (F4)?

**Comment by BabyFnord** [comment]
Yes, I have a three-pedal type VEC USB Footpedal `INFINITY USB`, and running `ioreg -w0 -l -p IOUSB` prints:
```
+-o VEC USB Footpedal@00400000  <class AppleUSBDevice, id 0x1000026b9, registered, matched, active, busy 0 (6 ms), retain 14>
        {
          "sessionID" = 348261090111265
          "iManufacturer" = 1
          "bNumConfigurations" = 1
          "idProduct" = 255
          "bcdDevice" = 288
          "Bus Power Available" = 250
          "USB Address" = 4
          "bMaxPacketSize0" = 8
          "iProduct" = 2
          "iSerialNumber" = 0
          "bDeviceClass" = 0
          "Built-In" = No
          "locationID" = 4194304
          "bDeviceSubClass" = 0
          "bcdUSB" = 272
          "USB Product Name" = "VEC USB Footpedal"
          "PortNum" = 4
          "non-removable" = "no"
          "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
          "bDeviceProtocol" = 0
          "IOUserClientClass" = "IOUSBDeviceUserClientV2"
          "IOPowerManagement" = {"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
          "kUSBCurrentConfiguration" = 1
          "Device Speed" = 0
          "USB Vendor Name" = "VEC "
          "idVendor" = 1523
          "IOGeneralInterest" = "IOCommand is not serializable"
          "IOClassNameOverride" = "IOUSBDevice"
        }
```
Checking its output per virtual keyboard, it does not send a particular keypress. I could not find a way to inspect its USB input but am willing to look into it, if someone can show me how to do it.

**Comment by kaixxx** [comment]
Information about this pedal is sparse. There is however a software for windows which can be used to send keypresses: https://solutioncenter.stenograph.com/en_US/audio/footpedalguides
This is what you want, but for mac. You would configure it to send Ctrl + Space, this controls start and stop of the audio in the noScribe editor. 
A quick search for mac only revealed this problem report: https://discussions.apple.com/thread/253300520?page=2&sortBy=best Not very helpful...

**Comment by BabyFnord** [comment]
Hmkay. I have access to another Mac with [Karabiner](https://github.com/pqrs-org/Karabiner-Elements) installed. Remembering its manufacturer agnostic feature to read keypresses from USB devices, maybe something useful shows up. More on this in a few days …

**Comment by BabyFnord** [comment]
@kaixxx On a side note to the foot pedal: With macOS, `CMD`+`SPACE` defaults to the OS search function (Spotlight search). While it is possible to deactivate this default behaviour for the time being, some other shortcut or key might be a better choice (as we discussed with @gernophil by mail some time ago) … 💁. Two more keys, for forward/backward navigation of segments, would speed up editing substantially. Thanks for considering!

**Comment by kaixxx** [comment]
> With macOS, CMD+SPACE defaults to the OS search function

Good point. We've also discussed a better alternative for macOS, something with SPACE also. But I forgot... Di you remember?

What would be your usecase for navigating through segments quickly? Should the audio keep playing or not? Will consider this.

**Comment by hanneshier** [comment]
> @kaixxx On a side note to the foot pedal: With macOS, `CMD`+`SPACE` defaults to the OS search function (Spotlight search). While it is possible to deactivate this default behaviour for the time being, some other shortcut or key might be a better choice (as we discussed with @gernophil by mail some time ago) … 💁. 

A quick and easy workaround in the meantime: you can set custom keyboard shortcuts for every menu title in an app via the macOS settings. Just go Settings > Keyboard > Keyboard Shortcuts > App Shortcuts. There, you can add a custom shortcut and limit it to certain apps. You just need to enter the correct menu title, "Play/Pause Audio" in this instance, and set a shortcut (hint: `OPT` + `SPACE` was not working for some reason).
