### ISSUE TITLE
noScribe doesn't launch - macOS Big Sur

### ISSUE THREAD

**Issue by Caaravane** [kaixxx/noScribe#56]
Hello !

I can't seem to get noScribe to open, only noScribe Edit will. The 0.4.4 version did not open at all when I tried downloading it so I got the 0.4 one but it's still not working despite having deactivated the gatekeeper for both the noscribe edit app and the "main" app. 
There's only 5go of storage free on my laptop after downloading noScribe, could it be the reason why it's not working ? (edit: just tried freeing up 20go and still not working)

![Capture d’écran 2024-05-01 à 17 33 27](https://github.com/kaixxx/noScribe/assets/168659710/9fd87273-f680-4004-9a85-429776839a9a)

**Comment by kaixxx** [comment]
Might be because your OS is too old. 
Try the version 0.4.5 beta linked here; it was compiled for older macs: https://github.com/kaixxx/noScribe/issues/49#issuecomment-2008060470

Please report back if it works!

**Comment by Caaravane** [comment]
Thanks for your answer ! I managed to install the 0.4.5 beta version, I tried transcribing a one-hour long interview and it started running normally but it was extremely slow and I gave up after 24hrs+ of waiting !  I guess my laptop (and/or OS) is too old.

**Comment by kaixxx** [comment]
Thank you for reporting back. Sadly, thats a limitation at the moment: If you want to run these advanced ai-models locally on your computer, you need an rather powerful machine. Maybe you have a friend with a newer laptop? The final check with the included editor of noScribe does not consume a lot of ressources, you can do that on your own computer. But the transcribing as such requires some computing power.
