### ISSUE TITLE
Using the GPU for whisper in noScribe

### ISSUE THREAD

**Issue by Telebohrer** [kaixxx/noScribe#6]
Dear Kai,

I am using whisper in this version: https://github.com/ProjectEGU/whisper-for-low-vram for transcription (because I have a 8GB NVIDIA), which runs much faster than with CPU.

I would like to try your noScribe because of the integration of speaker distinguishing. Is there any way to let it run on the GPU instead of the CPU? The whisper.ccp from ggerganov should also support that (https://github.com/ggerganov/whisper.cpp#nvidia-gpu-support-via-cublas) but I am not sure how to include that or set that option in noScribe.

Otherwise great work!

**Comment by GitNitneroc** [comment]
Could I find this CUDAS  main.exe somewhere, running on CPU when you have the available GPU seems like a waiste of time ? I just can't compile it myself since I'm on linux. BTW noScribe seems to be working fine through Proton (I guess Wine would be fine) !

**Comment by Telebohrer** [comment]
Hi, I tried to compile the main.exe with cuBLAS on.
noScribe still worked but nothing changed.
I don't know if it does not make a difference or if I compiled it wrongly...
Would also be interested to get a main.exe (and probably also a whisper.dll?) from somebody who can report that it worked.

**Comment by kaixxx** [comment]
I had do disable GPU support for now (at least for transcription, it may still work for speaker detection). It was causing problems. I will come back to this issue later.

**Comment by kaixxx** [comment]
Hi @Telebohrer 
A new version with cuda is out. Could you help testing it? See https://github.com/kaixxx/noScribe/discussions/50

**Comment by Kuiriel** [comment]
> Hi @Telebohrer A new version with cuda is out. Could you help testing it? See #50

Hullo! I'm testing your beautiful little program with transcribing interview answers for my wife to help her with her practice. It's a great time saver app, and the accuracy seems excellent.

Oh, and I'm using the latest CUDA version that you posted on the description page. It's working without a hitch so far on the 3 minute test video I tried. On a 4090 it's faster than the 3 minutes of the video, I'm pretty sure. Trying it out on a 19 minute video now, then the next test is a 2h audio clip. It looks like the longest time it takes is just loading pyannote and discrete_diarization (whatever those are!)

**Comment by kaixxx** [comment]
Closing this since CUDA has officially been integrated with verion 0.5 (and seems to work well).

**Comment by Kuiriel** [comment]
On further testing, while using the CUDA version you have provided in the description, it looks like it's using CPU while transcribing the video, with very little GPU utilization. Maximum GPU used over a 1h video recording was 4GB. There were infrequent occasional bursts in GPU utilization.

I'm happy to test noScribe out with some bigger language models that put the 24GB GPU through its paces. Any suggestions of what model to use? I've been running it on Precise and it looks like it does videos to text in only 25% to 50% of the duration of the video.

**Comment by kaixxx** [comment]
If you are getting transciption times of 15% ti 50% realtime (including speaker detection), you are most likely using the GPU at least for some steps of the process. 
One thing to check is that in the file `config.yml` in `C:\Users<USERNAME>\AppData\Local\noScribe\noScribe` both  "pyannote_xpu" and "whisper_xpu" are set to "cuda" (omit the quotes). 
Important: Close noScribe before making any changes to "config.yml".

"precise" is alread using the largest whisper-model from OpenAI.

This thread contains a lot of discussions on how to improve CUDA-performance: https://github.com/kaixxx/noScribe/discussions/50
Since I don't have a NVIDA-GPU, I can provide only limited help.
