### ISSUE TITLE
Fehler Windows: mkl_malloc: failed to allocate memory

### ISSUE THREAD

**Issue by avoxia17** [kaixxx/noScribe#68]
Hallo, 

ich habe mir die neueste Version von noScribe heruntergeladen. Leider funktioniert jedoch weder die Sprechererkennung noch kann ich die Interviews in einer präzisen Qualität transkribieren lassen.

Die Fehlermeldungen lauten wie folgt: 
Sprechererkennung: "Fehler im 2. Schritt - Erkennung der Sprecher:innen"
Qualität: "Fehler im 3. Schritt - Transkription. mkl_malloc: failed to allocate memory"

Ich habe leider nur für die Sprechererkennung einen Thread im Internet gefunden (jedoch von einem Person mit einem MAC und ich habe Windows). Dort wird geraten etwas in einer config.yml-Datei zu ändern. Allerdings kann ich diese Datei gar nicht finden, obwohl ich bereits eine Transkription habe durchlaufen lassen, wenn auch in der schlechteren Qualität.

Deshalb wäre sehr dankbar für Hilfe! Danke im Voraus :)

**Comment by kaixxx** [comment]
Hallo,

Es gibt ja jetzt zwei verschiedene Downloads für Windows, die normale Version und die für NVIDIA Grafikkarten mit CUDA. Ich vermute, du verwendest die Version für NVIDIA? Die Fehlermeldung deutet darauf hin. 
In diesem Fall kannst du die Verwendung der Grafikkartenbeschleunigung in der config.yml ausstellen. Wie du die Datei findest, ist hier beschrieben: https://github.com/kaixxx/noScribe#advanced-options
Schließe noScribe und ändere in der config.yml den Eintrag "pyannote_xpu" auf "cpu" (für die Sprecher:innenerkennung) und "whisper_xpu" auch auf "cpu" (für die Transkription). 

Hoffe, das hilft!

**Comment by kaixxx** [comment]
Funktioniert es?

**Comment by Yerfaens** [comment]
Hallo, ich habe dasselbe Problem: Es zeigt mir an "Fehler im 3. Schritt - Transkription. mkl_malloc: failed to allocate memory. Aber ich habe die "normale" Version und auch schon überprüft, dass bei "pyannote_xpu" und "whisper_xpu"  cpu steht.. Mein Laptop ist ziemlich alt (ca. 7,5 Jahre). Könnte es deshalb nicht gehen? Danke für eine kurze Rückmeldung.
Grüsse
Aens

**Comment by kaixxx** [comment]
@Yerfaens:  Weißt du, wie viel Arbeitsspeicher (RAM) dein Laptop hat? Das könnte das Problem sein. 

Hier gibt es eine neue Version von noScribe, die auch etwas weniger Speicherbedarf haben sollte: https://drive.switch.ch/index.php/s/HtKDKYRZRNaYBeI?path=%2FWindows%2Fnormal

Außerdem kannst du es mit der Einstellung "fast" bei "Qualität" ausprobieren. Das sollte auch etwas weniger Speicher benötigen.

**Comment by Yerfaens** [comment]
> [@Yerfaens](https://github.com/Yerfaens): Weißt du, wie viel Arbeitsspeicher (RAM) dein Laptop hat? Das könnte das Problem sein.
> 
> Hier gibt es eine neue Version von noScribe, die auch etwas weniger Speicherbedarf haben sollte: https://drive.switch.ch/index.php/s/HtKDKYRZRNaYBeI?path=%2FWindows%2Fnormal
> 
> Außerdem kannst du es mit der Einstellung "fast" bei "Qualität" ausprobieren. Das sollte auch etwas weniger Speicher benötigen.

Hat geklappt. Danke dir für deine schnelle Hilfe!

**Comment by kaixxx** [comment]
> Hat geklappt

Sehr schön. D.h. die neue Version läuft auch mit "precise"?
