### ISSUE TITLE
Window incorrectly sized at launch so appears to be missing start button

### ISSUE THREAD

**Issue by Kuiriel** [kaixxx/noScribe#71]
First time I used this I spent 5 minutes trying to figure out how to get the process going before realizing I was missing the start button entirely.

All I had to do was resize the window to be a little taller, then the start button appears on the bottom left. Easy.

Not sure if this is just because my resolution is 3440x1440 and the window was auto-sized. It hides the start button on each launch.

Very minor thing, but is a small barrier to entry on an otherwise incredibly easy to use app.

Thank you

**Comment by kaixxx** [comment]
The discussion of this issue continued here: https://github.com/kaixxx/noScribe/issues/95
