### ISSUE TITLE
noScribe not running on Monterey MacOS (Apple Silicon) 

### ISSUE THREAD

**Issue by yjeanrenaud** [kaixxx/noScribe#73]
Hi,

es geht um macOS 12.7.5 (21H1222) (Kernel-Version: Darwin 21.6.0) mit M1 SoC.

Die App öffnet nicht, weder noScribe in Version 0.50 noch noScribeEdit. Ohne Fehlermeldung und Nachfrage.
kein Klick, kein Control+Klick, auch nicht `open -n /Applications/noScribe.app`

ein direktes Starten des binaries via terminal führt zu folgendem Fehler:
```
 ./noScribe
[4108] Error loading Python lib '/Applications/noScribe.app/Contents/Frameworks/
Python': dlopen: dlopen(/Applications/noScribe.app/Contents/Frameworks/Python, 0
x000A): Symbol not found: (_mkfifoat)
Referenced from: '/Applications/noScribe. app/Contents/Frameworks/Python. framew
ork/Versions/3.9/Python'
Expected in: '/usr/lib/libSystem.B.dylib'


```

**Comment by gernophil** [comment]
Hey @yjeanrenaud,
Sorry für die späte Antwort. Ich glaub das Problem ist deine alte macOS-Version. Ich nutze 14.5 und scheinbar kann man nicht mehr so weit rückwärtskompatibel kompilieren. Dem muss ich mal auf den Grund gehen. Da die nen M1 hast, sollte es aber für dich auch möglich sein auf 14.5 zu updaten. Wäre das eine Alternative für dich? Due nutzt die arm64-Version oder? Ansonsten kannst du mal die x86_64_Legacy Version testen.

**Comment by yjeanrenaud** [comment]
Danke für die Antwort. Scheint wirklich mit dem OS zu tun zu haben. Ich fragte hier für Studierende, die im Rahmen einer Lehrveranstaltung das Problem hatten. Scheint mit einem Update verschwunden zu sein. Kurios.

**Comment by yjeanrenaud** [comment]
Closed
