### ISSUE TITLE
Error : unable to find a suitable format

### ISSUE THREAD

**Issue by juliendgros** [kaixxx/noScribe#74]
Hello, 
I installed Noscribe on Windows 10 but I'm having a problem. I am trying to transcribe an .mp3 file and the process stops at step 1 and returns the following error message: 

![image](https://github.com/user-attachments/assets/5c573938-1858-4e9b-8e1e-e75f4ccc688c)

Do you have any idea what is causing this problem? 
Thank you very much for your reply.
Have a nice day, 
Julien

**Comment by kaixxx** [comment]
Hi
It seems that the path to the audio is broken up at the space between "Julien" and "Gros". This should not happen. 
Please take a look in the folder "C:\Users\Julien Gros\AppData\Local\noScribe\noScribe\log\" There should be a logfile for Melissa. Could you post the contents here? This could help to identify the root of the problem.

You can, however, probably avoid this error if you move "Melissa.mp3" to a folder without a space in the path, e.g. to "C:\".

**Comment by juliendgros** [comment]
Hi
Thanks
Here are the contents of the logfile

whisper precise beam size: 1
whisper fast beam size: 1
whisper precise temperature: 0.0
whisper fast temperature: 0.0
whisper precise compute type: default
whisper fast compute type: default
timestamp_interval: 60000
timestamp_color: #78909C
=== CPU FEATURES ===
System: Windows
    VendorId                : GenuineIntel
    num_virtual_cores       : 4
    num_physical_cores      : 2
    num_threads_per_core    : 2
    num_cpus                : 1
    cache_line_size         : 64
    cache_L1_size           : 32768
    cache_L2_size           : 262144
    cache_L3_size           : 4194304
    OS_x64                  : True
    OS_AVX                  : True
    OS_AVX512               : False
    MMX                     : True
    x64                     : True
    ABM                     : True
    RDRAND                  : True
    BMI1                    : True
    BMI2                    : True
    ADX                     : True
    PREFETCHWT1             : False
    MPX                     : True
    SSE                     : True
    SSE2                    : True
    SSE3                    : True
    SSSE3                   : True
    SSE4.1                  : True
    SSE4.2                  : True
    SSE4.a                  : False
    AES                     : True
    SHA                     : False
    AVX                     : True
    XOP                     : False
    FMA3                    : True
    FMA4                    : False
    AVX2                    : True
    AVX512f                 : False
    AVX512pf                : False
    AVX512er                : False
    AVX512cd                : False
    AVX512vl                : False
    AVX512bw                : False
    AVX512dq                : False
    AVX512ifma              : False
    AVX512vbmi              : False
    AVX512vbmi2             : False
    AVX512vnni              : False

Conversion audio en cours...
ffmpeg.exe -loglevel warning -y -ss 0ms -to 1140000ms -i "C:/Users/Julien Gros/Downloads/Melissa.mp3" -ar 16000 -ac 1 -c:a pcm_s16le C:\Users\Julien Gros\AppData\Local\Temp\tmpaqindxggnoScribe\tmp_audio.wav
ffmpeg: [mp3 @ 000002418e06ae40] Estimating duration from bitrate, this may be inaccurate

ffmpeg: [NULL @ 000002418e087700] Unable to find a suitable output format for 'C:\Users\Julien'

ffmpeg: C:\Users\Julien: Invalid argument

ERROR: Erreur à l'étape 1 - conversion de l'audio.
ERROR: ffmpeg a renvoyé une erreur

**Comment by juliendgros** [comment]
I've tried it on another session with a username that doesn't contain spaces and it works fine. So that was the problem. I can't use the C: directory to send the output file (html) because noScribe won't let me (message telling me I'm not allowed to write to that folder). It's not very practical to have to change session but I'll manage! 
Thanks for all your help!

**Comment by kaixxx** [comment]
Now that I see the log, I think the problem is with the output path at the end of the ffmpeg-command (tmp_audio.wav). I should have put "quotation marks" around that like I did with the audio input. 
I've already fixed it in the code and will include it in the next release (which may take a few weeks). 
fix: 90489a051c3c7b444ce4c16279d06f7bfe8ad0ae
