### ISSUE TITLE
NoScribe shuts down 

### ISSUE THREAD

**Issue by FloTivi** [kaixxx/noScribe#76]
Hello.
Got the following problem: After selecting the file and get the settings done and pressing start its starts working first but then just shuts down. I tried it many times and with different files and settings but its always the same issue. Dont really know how to fix this, maybe you can help with this.
![image](https://github.com/user-attachments/assets/896d1f90-50e8-4104-b650-1c7debdbb24c)
The image was taking like 2 sec. before shut down.

**Comment by kaixxx** [comment]
That's strange. I wonder if there is a problem with the graphics card acceleration on your computer, e.g. not enough video memory or so. Try  this:
- Close noScribe
- Open the file C:\Users\\\<username>\AppData\Local\noScribe\noScribe\config.yml
- Is "whisper_xpu" set to "cuda"? If so, set it to "cpu"
- Save the file and restart noScribe

**Comment by FloTivi** [comment]
Well that worked. Thanks for the fast answer :)

**Comment by gernophil** [comment]
You will however probably suffer performance loss, if you disable CUDA. Maybe update you NVIDIA drivers and check, if CUDA works with those.
