### ISSUE TITLE
Mac ffmpeg: [Errno 86] Bad CPU type in executable

### ISSUE THREAD

**Issue by ludwik00** [kaixxx/noScribe#78]
Hello, 
wenn ich die Transkription starten möchte, erscheint sofort eine Fehlermeldung: 
"[Errno 86] Bad CPU type in executable: '/Applications/noScribe.app/Contents/Frameworks/ffmpeg'" 
Wie lässt sich dies beheben, bzw. lässt sich anhand dieser Fehlermeldung ausmachen, worin das Problem liegt? 
Vielleicht kann jemand behilflich sein. 
Beste Grüße Ludwig

**Comment by kaixxx** [comment]
Ich vermute, du bist auf einem Mac? Hier ist es sehr wichtig, dass du die richtige Version installierst, entweder für die älteren Macs mit Intel-Prozessor oder die neueren mit den Apple M1, M2, M3-Prozessoren. Das sind zwei verschiedene Downloads. Könnte es daran liegen?

**Comment by ludwik00** [comment]
Hm, ich habe auf dem neuesten MacBook (m3 Prozessor) die Version für neue Macs runtergeladen. 
Konnte es: 
A) an dem file-Format der Audio liegen (wobei ich hab m4a, mp4 und mp3 ausprobiert) 
Oder 
B) an einer nicht gegeben (wie auch immer gearteten) Erlaubnis auf Dateien des Macs zuzugreifen? 

Ist das Problem / der Fehlercode schonmal aufgetreten? 

Liebe Grüße und vielen Dank für die schnelle Antwort :)

**Comment by gernophil** [comment]
Also vielleicht gab es ffmpeg damals nur als x86_64 Version. Das heißt noScribe ist für die neuen CPUs aber ffmpeg (ein Unterprogramm) nicht. Vielleicht muss ich das demnächst mal aktualisieren, aber ich geh davon aus, dass das das Problem ist. Du müsstest Rosetta2 installieren. Das is ein Apple-eigener Übersetzer von Intel zu Arm CPUs. Sollte eigentlich automatisch angestoßen werden die Installation. Ansonsten Google mal Rosetta2 installieren. Sollte recht einfach sein.

**Comment by kaixxx** [comment]
Soweit ich weiß, gibt es keine (offizielle) Version von ffmpeg für ARM: https://evermeet.cx/ffmpeg/apple-silicon-arm

Allerdings wundert mich, das bisher noch niemand dieses Problem hatte. Haben alle Rosetta2 installiert?

**Comment by gernophil** [comment]
Ich denke ja. Es gibt so viele Apps, die noch auf x86_64 laufen. Und eigentlich wird man so als man so eine App startet direkt dazu aufgefordert Rosetta2 zu installieren.

**Comment by BabyFnord** [comment]
Gleiches Problem, ohne Rosetta so gelöst:
1. Im Finder `CMD + Shift + g` eingeben und diesen Dateipfad ansteuern `/Applications/noScribe.app/Contents/Frameworks/ffmpeg`.
2. Diese Version von `ffmpeg` gegen die angehängte Version* austauschen [ffmpeg.zip](https://github.com/user-attachments/files/16782715/ffmpeg.zip)
3. `noScribe` starten und los geht's …

*Die angehängte Version von `ffmpeg` …
```
ffmpeg version 7.0.2 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
```
stammt von einem M2Pro via [Homebrew](https://brew.sh) (ffmpeg--7.0.2.arm64_sonoma.bottle.tar.gz).

**Comment by gernophil** [comment]
Ah, gut zu wissen, dass es bei Homebrew ne arm64-Version gibt.

**Comment by BabyFnord** [comment]
Jep. Hab den Beitrag noch für den Editor ergänzt.
