### ISSUE TITLE
Fehler beim Öffnen in MS Word: Laufzeitfehler 5346

### ISSUE THREAD

**Issue by BabyFnord** [kaixxx/noScribe#8]
Hello,

wenn ich ein Transkript in MS Word (MS Office v16.0.xxxx) öffne, erscheint die Fehlermeldung:
```
Microsoft Visual Basic
Laufzeitfehler '5346': Die Funktion der angegebenen Taste kann von Word nicht geändert werden.
```
Vermutung: Hängt mit der PlayAlong-Funktion zusammen. Wie lässt sich das beheben?

Danke :) BF

**Comment by kaixxx** [comment]
Hmm, seltsam. Leider kann ich den Fehler nicht reproduzieren. Ich habe es gerade extra nochmal auf einem älteren Computer mit Word 2013 probiert (andere Versionen habe ich gerade nicht verfügbar). 
Ja, das Problem hat mit der PlayAlong-Funktion zu tun. 
Genauer: Beim Laden des Dokuments wird automatisch die Prozedur "Register_Event_Handler()" (im Modul "noScribe_module") aufgerufen. Dort werden zwei Hotkeys registriert: Strg + Space für PlayAlong, Alt + r für die Anzeige der "Reliability". Dabei scheint es ein Problem zu geben. 
Es wäre super hilfreich, wenn du diese Funktion mal debuggen könntest (mit F8 = Einzelschritt), um das Problem einzugrenzen. Aber das setzt natürlich ein klein wenig VBA-Kenntnisse voraus.

**Comment by BabyFnord** [comment]
Leider kann ich den Fehler nicht reproduzieren. Mein Laptop ist zu alt für eine Transkription in vernünftigem Zeitrahmen, deswegen muss ich auf Rechner in der Uni ausweichen. Wenn ich das Transkript zu Hause mit der gleichen Datei bearbeiten will, stimmt die Verknüpfung in Zeile 3 natürlich nicht mehr; das kann ich in Word nicht neu verknüpfen. Auf `CTRL+SPACE` kommt keine Reaktion. Deswegen ein Vorschlag für die Integration von Zeitmarken, siehe https://github.com/kaixxx/noScribe/discussions/12 …

**Comment by kaixxx** [comment]
Wenn die PlayAlong-Funktion die Audiodatei nicht am angegebenen Ort findet, öffnet sich automatisch ein Dateidialog, mit dem man die Audiodatei suchen und neu verknüpfen kann. 
Aber ja, das Kernproblem ist wohl, dass die Makros erst gar nicht starten - warum auch immer. 

Ich überlege, in einer zukünftigen Version die Option zu integieren, das Transkript auch als normale Textdatei ausgeben zu lassen (vor allem für jene, die kein Word nutzen). Da würde ich dann auch Zeitmarken in den Text integrieren, danke für die Anregung.

**Comment by BabyFnord** [comment]
> Es wäre super hilfreich, wenn du diese Funktion mal debuggen könntest (mit F8 = Einzelschritt), um das Problem einzugrenzen. Aber das setzt natürlich ein klein wenig VBA-Kenntnisse voraus.

Bitteschön:
```
Sub Register_Event_Handler()
    Set noScribe = New noScribe_class
        
    ' Add hotkey for macro PlayAlong()
    With Application
        .CustomizationContext = ThisDocument
```
        .KeyBindings.Add KeyCode:=BuildKeyCode(wdKeyControl, wdKeySpacebar), _
        KeyCategory:=wdKeyCategoryCommand, _
        Command:="PlayAlong"
```
        .KeyBindings.Add KeyCode:=BuildKeyCode(wdKeyAlt, wdKeyR), _
        KeyCategory:=wdKeyCategoryCommand, _
        Command:="ShowConfidenceLevel"
    End With
End Sub
```
Das Code-Fragment in der Mitte wird gelb markiert angezeigt.

**Comment by kaixxx** [comment]
Interessant. Gut ist, dass die Makros schon mal grundsätzlich laufen und nicht blockiert werden. 
Irgendetwas scheint bei der konkreten Zuweisung des Tastenkürzels schief zu laufen.

Du könntest es mal manuell versuchen: 
- Rechte Maustaste auf die Menüleiste oben in Word, dann "Menüband anpassen", unten auf "Tastenkombinationen > Anpassen" klicken. 
- Jetzt unter "Befehl" "Makros" auswählen und unter "Speichern unter" den Namen des geöffneten Transkripts. Dann müsste rechts in der Liste "Makros" der Eintrage "PlayAlong" auftauchen > dieses auswählen. 
- Dann im Feld "Neue Tastenkombination" Strg und Leertaste drücken. 
- Mit dem Klick auf "Zuordnen" links unten müsste das Tastenkürzel jetzt registriert sein (für dieses eine Dokument). 

=> Ich hoffe auf eine Fehlermeldung irgendwo in diesem Prozess, die klarer macht, wo das Problem eigentlich liegt.

**Comment by kaixxx** [comment]
With version 0.4b I moved away from using Word macros. NoScribe no comes with its own editor.

**Comment by NickN870** [comment]
Hallo Kai, bei mir wird der gleiche Fehler angezeigt. Allerdings kann das erst seit wenigen Tagen sein, da ich die Dateien in den letzten Monaten (seit der Transkription) ohne Probleme öffnen und bearbeiten konnte. Die von Dir vorgeschlagene und beschriebene Lösung funktioniert bei mir leider nicht. Es taucht kein PlayAlong in der Liste rechts auf. Zudem habe ich eine ganze Reihe von Datein, die sich überhaupt nicht mehr öffnen lassen. Somit könnte ich diesen Lösungsweg ohnehin nicht anwenden.

Gibt es einen Weg, wie ich die Dateien noch retten/wieder lesbar machen kann?

Vielen Dank im Voraus.

**Comment by kaixxx** [comment]
Zunächst einmal: Du arbeitest noch mit der (sehr) alten Version von noScribe, die Worddateien (.docm) ausgibt, richtig?

Wenn "PlayAlong" nicht wie oben beschrieben in der Liste der Makros auftaucht, dann vermute ich, dass die Makros komplett blockiert sind aufgrund der Sicherheitseinstellungen in Word. Hier könntest du mal googeln, wie man die Sicherheitseinstellungen in Word (zumindest temporär) so ändern kann, dass auch unsignierte Makros ausgeführt werden dürfen. 

Gravierender scheint mir aber:
>  habe ich eine ganze Reihe von Datein, die sich überhaupt nicht mehr öffnen lassen

Was passiert denn da? Fehlermeldungen?

**Comment by NickN870** [comment]
Ja, das scheint der Fall zu sein. Ich verwende NoScribe jetzt schon eine Weile und habe mich noch nicht die neueste Version bemüht.

Ich habe im "Trust Center" von Word die Einstellungen jetzt so geändert, dass alle Macros aktiviert werden und den Zugriff auf VBA erlaubt. Damit kann ich zumindest einen Teil der Dateien öffnen, allerdings nicht alle. Seltsam ist, dass manche älteren Transkriptionen funktionieren, andere nicht und einige aus den letzten Monaten ebenfalls mal so, mal so.

Wenn ich die Dateien, die nicht funktionieren, öffnen möchte, dann wird zeigt er "Microsoft Word wird gestartet", "Add-ins werden geladen (2/2)" und "Citavi Word Add-in 6.19.1.11" und dann passiert nichts weiter. Word geht nicht auf und es kommt auch keine Fehlermeldung.

**Comment by NickN870** [comment]
Wenn es funktioniert, kommt als nächstes "Wird verarbeitet..." und dann öffnet sich Word ganz normal.

**Comment by kaixxx** [comment]
Ich würde Word mal starten ohne Dokument und dann über "Datei > Öffnen" das Transkript laden. Dann müsste ja zumindest eine Fehlermeldung kommen. 

Generell würde ich sehr zum Umstieg auf die aktuelle Version von noScribe raten. Es hat sich viel getan seit damals ;)

**Comment by NickN870** [comment]
In dem Fall wird nur angezeigt: "Dieser Speicherort kann nicht mit diesem Programm geöffnet werden. Versuchen Sie einen anderen Speicherort."

Für die kommenden Transkriptionen werde ich definitiv auf die aktuelle Version umsteigen ;-) Allerdings wäre es trotzdem schön, die letzten ca. 40 Transkriptionen zu retten. Hast Du noch weitere Ideen?

**Comment by kaixxx** [comment]
Die Fehlermeldung ist seltsam. Ich frage mich, ob es tatsächlich an dem "Speicherort" liegt, also dem Ordner, in dem das Transkript liegt. Kopiere doch mal eine Datei in den normalen Dokumente-Ordner und versuche, sie von dort zu öffnen. (Auch das könnte mit Sicherheitseinstellungen in Word zusammenhängen.)
Ansonsten: Wenn es nicht um super vertrauliche Daten geht, könntest du mir eine Datei, die bei dir nicht funktioniert, per Email an kai.droege [ät] hslu.ch schicken. Dann schaue ich sie mir gerne mal genauer an.

**Comment by NickN870** [comment]
Es hat geklappt. Wenn ich die Dateien auf den Desktop ziehe und dort öffne, funktioniert es. Wenn ich Datei allerdings als ".docx" speichere und wieder in den alten Ordner (externe Festplatte) ziehe, kann ich sie dort nicht mehr öffnen. Als "txt" gespeichert funktioniert es auch von der Festplatte aus. Es liegt demnach mit großer Sicherheit an den Word Einstellungen bzw. den Makros.

Mein Problem ist also gelöst. Vielen Dank dafür!!! Hätte es nicht geklappt, wäre ich wieder ewig mit der Transkription beschäftigt.

Aber paar Fragen bleiben: Auf der einen Seite kann ich einige .docm-Dateien mit den veränderten Word-Einstellungen öffnen, andere allerdings nicht. Und: Wieso ist der Speicherort auf einmal problematisch, wenn es doch davor nie ein Problem dargestellt hat?

**Comment by NickN870** [comment]
Danke nochmals. 

Da es sich um sensible, personenbezogene Daten handelt, kann ich Dir nicht ohne Weiteres eine Datei schicken. Falls es allerdings wichtig für die Weiterentwicklung von NoScribe ist und Du dem Problem auf den Grund gehen möchtest, können wir DSGVO-konforme Lösung finden.

**Comment by kaixxx** [comment]
Es gab viele Probleme mit Viren in Word Makros, die mit Word-Dokumenten per Email oder auf anderen Wegen verteilt wurden (auch USB-Sticks etc., daher vermutlich die Probleme mit der externen Festplatte). Deshalb hat Microsoft immer mehr Sicherheitsmaßnahmen eingeführt und die Verwendung von Makros mehr und mehr verunmöglicht. Das war ein Hauptgrund für mich, in noScribe auf ein anderes Ausgabeformat zu wechseln.

Was mich allerdings sehr wundert: Sobald du das Transkript mit "Speichern unter" als normales Worddokument speicherst (.docx), sollten eigentlich alle Makros entfernt sein und es sollte problemlos möglich sein, diese Datei auf einer externen Festplatte abzulegen. (Nur die Dateiendung zu ändern reicht aber vermutlich nicht, es muss schon "Speichern unter" sein.)

Eine andere Option: Speichern im OpenDocument Format (.odt).

**Comment by NickN870** [comment]
Ich habe die Dateien jetzt zur Sicherheit im txt.-Format gespeichert und zusätzlich noch auf einer anderen Festplatte. 
Das "Umspeichern" in docx. funktioniert bringt leider nicht die gewünscht Lösung. Mir ist aber auch so geholfen.
