### ISSUE TITLE
"Error creating temporary audio file. Exceptions must derive from BaseException"

### ISSUE THREAD

**Issue by runa313** [kaixxx/noScribe#80]
After transcribing the first two sentences  of a 30min-video the error message 
"Error creating temporary audio file. Exceptions must derive from BaseException" came up.

It did transcribe a couple of sentences very perfectly, and also claimed "Transcription finished".

But as I mentioned the issue is that it did not transcribe the whole video.

![image_2024-08-22_213044936](https://github.com/user-attachments/assets/eb51db00-26f9-4238-bc74-89f8d3479b31)

I would like to rely on this software if possible, since it is the only popular open source program. Thanks

running on:  old Thinkbook, Windows 10

**Comment by kaixxx** [comment]
This is a strange error and I have no idea where it is coming from. A wild guess would be that your machine might be running out of memory. Please try switching the quality to "fast". This will reduce the quality of the transcription, but uses much less memory. If we know that this is the issue, we can try some other things.

**Comment by gernophil** [comment]
Be aware that this is an error from `noScribeEdit`, not `noScribe` itself. Maybe the transcription process itself was incomplete and that's why it can't be opened in `noScribeEdit`?

**Comment by kaixxx** [comment]
> Be aware that this is an error from noScribeEdit

Ah, yes, so please forget everything I wrote above.

It seems tthat we have two problems here: 
- noScribe not fully transcribing the whole file
- noScribeEdit not beeing able to open the original audio/video file.

Both errors point to an issue with the original video file which may be corrupted. 
@runa313: Can you play the full video (not only the first seconds) with a video player like VLC or Windows Media Player?

**Comment by runa313** [comment]
Thank you @kaixxx and @gernophil. You guys are absolutely fantastic.
Yes the video file was corrupted since my internet had been unstable during the download.

Thanks a ton for providing this software for free, maintaining it, and answering such questions.

Here a quote for you.
“A society where no one must chase money, for money has no value, and all people are entitled to everything, and everyone works not for money but for the honor of contributing to mankind. People at that time will be motivated by honor and love of country and mankind, and not by greed and love of self and the world.”~ Aba Al-Sadiq, The Goal of the Wise.

**Comment by kaixxx** [comment]
Nice to hear that the issue was resolved. Thank's for the kind words!
