### ISSUE TITLE
Mac M2 Pro - multiple issues

### ISSUE THREAD

**Issue by neonsatire** [kaixxx/noScribe#82]
Hi, 

I recently tried to install noscribe (version 0.5.0) several times on my Mac (M2 Pro Sonoma 14.1.1), and have been running into a series of issues: the first of which was an ffmpeg error (like described here: https://github.com/kaixxx/noScribe/issues/78). 

I used the solution @BabyFnord offered up, but after that ran into an error in step 2 (identifying the speakers). Turning off speaker detection, I ran into Error in step 3 ([Errno 2] No such file or directory:).

What can I do?

Thanks for any help! 
[noscribelog.pdf](https://github.com/user-attachments/files/16994966/noscribelog.pdf)

**Comment by gernophil** [comment]
> I recently tried to install noscribe (version 0.5.0) several times on my Mac (M2 Pro Sonoma 14.1.1), and have been running into a series of issues: the first of which was an ffmpeg error (like described here: #78).

The first one can be solved by installing Rosetta (which is an official intel to arm translator from Apple). Maybe we will include an arm64 specific version off ffmpeg in to next release. You can install Rosetta2 manually follwing this:
https://apple.stackexchange.com/questions/457472/how-to-install-rosetta-2-manually

> I used the solution @BabyFnord offered up, but after that ran into an error in step 2 (identifying the speakers). Turning off speaker detection, I ran into Error in step 3 ([Errno 2] No such file or directory:).

I guess the second issue comes from the solution of the first. Try to redownload noScribe, install Rosetta2 and run it without changing any internal files. I looks like the ffmpeg version you manually introduced is missing some libraries.

**Comment by neonsatire** [comment]
Thanks for the quick reply, this worked for me!

(In case someone else is having this issue, I wasn't asked to install rosetta 2 for the program, and spent a stupid amount of time googling installing rosetta 2 - since most pages talk about installing it 'manually' via software update. Just follow the link above and do it in Terminal.)

**Comment by gernophil** [comment]
Yes, I also don't know, why it doesn't ask for being installed in noScribe. It should be triggered by `x86_64` executables, but maybe, because the app itself is an `arm64` and the `x86_64` ffmpeg is just hidden somewhere in the app.

Maybe we should mention this in the README.md, @kaixxx?

**Comment by gernophil** [comment]
And great to hear it worked :).

**Comment by kaixxx** [comment]
>Maybe we should mention this in the README.md

Yes, this would be very useful. Go ahead if you want 😃

**Comment by BabyFnord** [comment]
While it's perfectly debatable and somewhat easier to rely on Rosetta to emulate `x86_64` on Apple Silicon for the audio conversion part, I'd rather install `ffmpeg` via [Homebrew](https://brew.sh/) and exchange `ffmpeg` and `ffplay` for proper `arm64` versions (as per https://github.com/kaixxx/noScribe/issues/78#issuecomment-2315101099). At least for the time being … 🤷‍♂️

**Comment by gernophil** [comment]
I tend to disagree :). Actually, I believe the majority of Apple silicon's have installed Rosetta2 anyway, since you need it for a Lott of stuff. Since it's perfectly integrated into macOS's environment, the only reason not to is due to performance issues. And for ffmpeg that's not an issue. Exchanging packages in an .app is more error prone. And the ffmpeg from homebrew does not seem to be a standalone executable. If you exchange, you should at least use one of the standalone builds from osxexperts.net or similar

**Comment by gernophil** [comment]
More is described [here](https://www.osxexperts.net):

> Homebrew is an easy way to compile FFmpeg files but sadly they are not static.
Static means you can copy the FFmpeg file anywere you want. It has no dependencies compared to a dynamically build like Homebrew does.

One widely used static build of ffmpeg besides that from osxexperts.net can be found at ffmpeg.martin-riedl.de. I guess we'll either use one of those or build it ourselves in the next release, but this might be a little overkill.

**Comment by gernophil** [comment]
osxexperts.net state that "[t]he provided FFmpeg files are for educational purposes only". Not sure, if we can use them. [Martin Riedl](https://gitlab.com/martinr92) does not have such a disclaimer. Maybe we could ask him. What are your thoughts on that @kaixxx?

**Comment by kaixxx** [comment]
The builds from Martin Riedl look good. The are also signed, which might be a bonus. 
I'm open for both solutions: rosetta or special builds.

**Comment by BabyFnord** [comment]
> One widely used static build of ffmpeg […] can be found at [ffmpeg.martin-riedl.de](https://ffmpeg.martin-riedl.de/). 

Pretty neat find 👍. I wasn't aware of FFmpeg's reliance on libraries, doh. FWIW I've adapted https://github.com/kaixxx/noScribe/issues/78#issuecomment-2315101099) to use https://ffmpeg.martin-riedl.de binaries, as a Rosetta-independent fix for the time being 😺.

**Comment by gernophil** [comment]
> I wasn't aware of FFmpeg's reliance on libraries, doh.

Me neither since the error report of @neonsatire :). Thanks for updating your solution. (And sorry for editing your comment, I wanted to answer. Didn't even know, I could edit your comments :D.)

**Comment by neonsatire** [comment]
I'm very glad I got to learn something. :)
