### ISSUE TITLE
NoScribe unter Windows 10: Start Button nicht sichtbar

### ISSUE THREAD

**Issue by Hachikozero** [kaixxx/noScribe#89]
Hi, 

ich bin naive Anwenderin ohne jegliche Programmierkenntnisse und würde gern NoScribe (Version 0.5.1) unter Windows 10 nutzen.  
Nach erfolgreicher Installation erhalte ich in der Anwendung dauerhaft die Fehlermeldung "[Errno 2] No such file or directory" . 
Natürlich hab ich gegengecheckt, dass die Datei existiert. Ich hab auch ein bisschen mit Dateinamen und Speicherort, sowie "Start" "Stop" Zeiten rumgespielt.
Transkribieren möchte ich große (>60min) MP3 Dateien, hab aber auch kleine ausprobiert (ca. 10 min), keine Änderung.

Hat hier jmd nen Tipp für mich?

**Comment by kaixxx** [comment]
An welcher Stelle im Prozess kommt denn diese Fehlermeldung? Ein Screenshot wäre hilfreich (unten auf "Paste, drop, or click to add files" klicken).

**Comment by Hachikozero** [comment]
![Screenshot 2024-10-11 123135](https://github.com/user-attachments/assets/6711264e-540e-49f6-ba87-7eee15d7e7a0)
![Screenshot2](https://github.com/user-attachments/assets/1779e63a-37d1-420b-9196-8618b7ccf94b)

Hi, danke schonmal :D 

Die Meldung kommt unmittelbar nach Eingabe. Da liegt keine Sekunde dazwischen

**Comment by kaixxx** [comment]
OK, das Problem ist ziemlich simpel: Sie sehen den Start-Button gar nicht, um die Transkription zu beginnen. Einfach das Fenster etwas größer ziehen, dann erscheint links unten der Button. 

Ich hatte den Fall schon einmal, kommt offenbar nur unter Windows 10 vor. Ich muss mal schauen, ob sich das in der nächsten Version lösen lässt.

**Comment by kaixxx** [comment]
Nein, das ist wirklich ein blöder Fehler auf Win10. Ich muss mal meinen alten Computer wieder aktivieren und nach einer Lösung suchen.

**Comment by kaixxx** [comment]
Der Fehler ist leider nicht auf Windows 10 beschränkt. Ich suche nach einer Lösung für das nächste release (bis dahin steht zumindest eine Warnung im readme). 
Die Diskussion geht hier weiter: https://github.com/kaixxx/noScribe/issues/96 Deshalb schließe ich dieses Issue.
