### ISSUE TITLE
Problems with avast (anti-virus) during installation 

### ISSUE THREAD

**Issue by Rafacente** [kaixxx/noScribe#9]
I was very excited to use noscribe for my qualitative interview analysis but unfortunately I cannot install it proppery. 
I receive continuous warnings from microsoft and avast (anti-virus) and the instalation process stops without any option to allow for its continuation. 
Do you have any recommendation how I can install it successfully? 
Many thanks in advance! 
Rafa

**Comment by kaixxx** [comment]
It seems that avast is messing with the installation process. Try to disable avast and try again.
