### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IgorGeraskin22** [kaixxx/noScribe#93]
Hello!
Excellent program. Thank you.
I have a question for you, how did you compile such a large project? How did you do it? How did you create the executable file?
I am a student and this will be a good experience for me.
Thank you.

**Comment by gernophil** [comment]
Wie used PyInstaller for this. For noScribe a little additional configuration was necessary, but all in all this package is well documented. You might just wanna take a look.

**Comment by kaixxx** [comment]
On Windows, we use pyinstaller to compile the app and the Nullsoft Scriptable Install System NSIS to generate the setup file. Creating such a large setup file is indeed a problem, at least with free tools. But there is a special version on NSIS supporting files over 2GB: https://sourceforge.net/projects/nsisbi/ This is what I use, works well.
