### ISSUE TITLE
Find and Replace in Editor

### ISSUE THREAD

**Issue by Lod3** [kaixxx/noScribe#96]
Currently, using NoScribe (with WhisperV2 ) to transcribe our IIF meetings , the word IIIF is transcribed as AAAF.  
On a side note when testing Whisper V3 mentiones of IIIF are correctly transcribed. 
Regardless if NoScribe should use Whisper V2 or V3, a find and replace function in the editing menu would be very useful to quickly replace wrongly transcribed words that appear multiple times.

![noScribeEdit_9Tdw4bO1oX](https://github.com/user-attachments/assets/47418bca-fbf8-4894-8b24-abe116b92c23)

Thank you, 
<3 NoScribe

**Comment by kaixxx** [comment]
Yes, implementing find and replace in the noScribe editor was already in the back of my mind too, good suggestion. 

You can, however, also try something else, in case you want to have 'IIIF' transcribed correctly in the future: 
- Locate the file 'prompt.yml' in the installation folder of noScribe
- Edit this file and add an entry for your language (dutch?): `nl: "IIIF"`. You can also try adding a complete sentence. This acts as an example showing the AI how to transcribe the audio. 

I hope that this is going to resolve your issue. Make sure, however, to also check later passages in your transcript. Sometimes the AI forgets the initial prompt after a while.

**Comment by gernophil** [comment]
As a workaround, shouldn't it be possible to open the html file with any text editor and replace all AAAF with IIIF. I'd say the chances of destroying the html code by doing this are nearly 0.

**Comment by gernophil** [comment]
I would need to check tomorrow, but I don't think you will. Edit the html in a plain text editor, safe it and then open it again noScribeEditor.

**Comment by kaixxx** [comment]
I have now added a Search & Replace feature to the editor for the upcoming release of vers. 0.6
Thanks for the suggestion!
